using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    // 010 Grpcsharp_init                           ModelClassType grpcsharp_init_delegate grpcsharp_init_delegate grpcsharp_init_delegate Pointer
    // 018 Grpcsharp_shutdown                       ModelClassType grpcsharp_shutdown_delegate grpcsharp_shutdown_delegate grpcsharp_shutdown_delegate Pointer
    // 020 Grpcsharp_version_string                 ModelClassType grpcsharp_version_string_delegate grpcsharp_version_string_delegate grpcsharp_version_string_delegate Pointer
    // 028 Grpcsharp_batch_context_create           ModelClassType grpcsharp_batch_context_create_delegate grpcsharp_batch_context_create_delegate grpcsharp_batch_context_create_delegate Pointer
    // 030 Grpcsharp_batch_context_recv_initial_metadata ModelClassType grpcsharp_batch_context_recv_initial_metadata_delegate grpcsharp_batch_context_recv_initial_metadata_delegate grpcsharp_batch_context_recv_initial_metadata_delegate Pointer
    // 038 Grpcsharp_batch_context_recv_message_length ModelClassType grpcsharp_batch_context_recv_message_length_delegate grpcsharp_batch_context_recv_message_length_delegate grpcsharp_batch_context_recv_message_length_delegate Pointer
    // 040 Grpcsharp_batch_context_recv_message_next_slice_peek ModelClassType grpcsharp_batch_context_recv_message_next_slice_peek_delegate grpcsharp_batch_context_recv_message_next_slice_peek_delegate grpcsharp_batch_context_recv_message_next_slice_peek_delegate Pointer
    // 048 Grpcsharp_batch_context_recv_status_on_client_status ModelClassType grpcsharp_batch_context_recv_status_on_client_status_delegate grpcsharp_batch_context_recv_status_on_client_status_delegate grpcsharp_batch_context_recv_status_on_client_status_delegate Pointer
    // 050 Grpcsharp_batch_context_recv_status_on_client_details ModelClassType grpcsharp_batch_context_recv_status_on_client_details_delegate grpcsharp_batch_context_recv_status_on_client_details_delegate grpcsharp_batch_context_recv_status_on_client_details_delegate Pointer
    // 058 Grpcsharp_batch_context_recv_status_on_client_error_string ModelClassType grpcsharp_batch_context_recv_status_on_client_error_string_delegate grpcsharp_batch_context_recv_status_on_client_error_string_delegate grpcsharp_batch_context_recv_status_on_client_error_string_delegate Pointer
    // 060 Grpcsharp_batch_context_recv_status_on_client_trailing_metadata ModelClassType grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate Pointer
    // 068 Grpcsharp_batch_context_recv_close_on_server_cancelled ModelClassType grpcsharp_batch_context_recv_close_on_server_cancelled_delegate grpcsharp_batch_context_recv_close_on_server_cancelled_delegate grpcsharp_batch_context_recv_close_on_server_cancelled_delegate Pointer
    // 070 Grpcsharp_batch_context_reset            ModelClassType grpcsharp_batch_context_reset_delegate grpcsharp_batch_context_reset_delegate grpcsharp_batch_context_reset_delegate Pointer
    // 078 Grpcsharp_batch_context_destroy          ModelClassType grpcsharp_batch_context_destroy_delegate grpcsharp_batch_context_destroy_delegate grpcsharp_batch_context_destroy_delegate Pointer
    // 080 Grpcsharp_request_call_context_create    ModelClassType grpcsharp_request_call_context_create_delegate grpcsharp_request_call_context_create_delegate grpcsharp_request_call_context_create_delegate Pointer
    // 088 Grpcsharp_request_call_context_call      ModelClassType grpcsharp_request_call_context_call_delegate grpcsharp_request_call_context_call_delegate grpcsharp_request_call_context_call_delegate Pointer
    // 090 Grpcsharp_request_call_context_method    ModelClassType grpcsharp_request_call_context_method_delegate grpcsharp_request_call_context_method_delegate grpcsharp_request_call_context_method_delegate Pointer
    // 098 Grpcsharp_request_call_context_host      ModelClassType grpcsharp_request_call_context_host_delegate grpcsharp_request_call_context_host_delegate grpcsharp_request_call_context_host_delegate Pointer
    // 0A0 Grpcsharp_request_call_context_deadline  ModelClassType grpcsharp_request_call_context_deadline_delegate grpcsharp_request_call_context_deadline_delegate grpcsharp_request_call_context_deadline_delegate Pointer
    // 0A8 Grpcsharp_request_call_context_request_metadata ModelClassType grpcsharp_request_call_context_request_metadata_delegate grpcsharp_request_call_context_request_metadata_delegate grpcsharp_request_call_context_request_metadata_delegate Pointer
    // 0B0 Grpcsharp_request_call_context_reset     ModelClassType grpcsharp_request_call_context_reset_delegate grpcsharp_request_call_context_reset_delegate grpcsharp_request_call_context_reset_delegate Pointer
    // 0B8 Grpcsharp_request_call_context_destroy   ModelClassType grpcsharp_request_call_context_destroy_delegate grpcsharp_request_call_context_destroy_delegate grpcsharp_request_call_context_destroy_delegate Pointer
    // 0C0 Grpcsharp_composite_call_credentials_create ModelClassType grpcsharp_composite_call_credentials_create_delegate grpcsharp_composite_call_credentials_create_delegate grpcsharp_composite_call_credentials_create_delegate Pointer
    // 0C8 Grpcsharp_call_credentials_release       ModelClassType grpcsharp_call_credentials_release_delegate grpcsharp_call_credentials_release_delegate grpcsharp_call_credentials_release_delegate Pointer
    // 0D0 Grpcsharp_call_cancel                    ModelClassType grpcsharp_call_cancel_delegate grpcsharp_call_cancel_delegate grpcsharp_call_cancel_delegate Pointer
    // 0D8 Grpcsharp_call_cancel_with_status        ModelClassType grpcsharp_call_cancel_with_status_delegate grpcsharp_call_cancel_with_status_delegate grpcsharp_call_cancel_with_status_delegate Pointer
    // 0E0 Grpcsharp_call_start_unary               ModelClassType grpcsharp_call_start_unary_delegate grpcsharp_call_start_unary_delegate grpcsharp_call_start_unary_delegate Pointer
    // 0E8 Grpcsharp_call_start_client_streaming    ModelClassType grpcsharp_call_start_client_streaming_delegate grpcsharp_call_start_client_streaming_delegate grpcsharp_call_start_client_streaming_delegate Pointer
    // 0F0 Grpcsharp_call_start_server_streaming    ModelClassType grpcsharp_call_start_server_streaming_delegate grpcsharp_call_start_server_streaming_delegate grpcsharp_call_start_server_streaming_delegate Pointer
    // 0F8 Grpcsharp_call_start_duplex_streaming    ModelClassType grpcsharp_call_start_duplex_streaming_delegate grpcsharp_call_start_duplex_streaming_delegate grpcsharp_call_start_duplex_streaming_delegate Pointer
    // 100 Grpcsharp_call_send_message              ModelClassType grpcsharp_call_send_message_delegate grpcsharp_call_send_message_delegate grpcsharp_call_send_message_delegate Pointer
    // 108 Grpcsharp_call_send_close_from_client    ModelClassType grpcsharp_call_send_close_from_client_delegate grpcsharp_call_send_close_from_client_delegate grpcsharp_call_send_close_from_client_delegate Pointer
    // 110 Grpcsharp_call_send_status_from_server   ModelClassType grpcsharp_call_send_status_from_server_delegate grpcsharp_call_send_status_from_server_delegate grpcsharp_call_send_status_from_server_delegate Pointer
    // 118 Grpcsharp_call_recv_message              ModelClassType grpcsharp_call_recv_message_delegate grpcsharp_call_recv_message_delegate grpcsharp_call_recv_message_delegate Pointer
    // 120 Grpcsharp_call_recv_initial_metadata     ModelClassType grpcsharp_call_recv_initial_metadata_delegate grpcsharp_call_recv_initial_metadata_delegate grpcsharp_call_recv_initial_metadata_delegate Pointer
    // 128 Grpcsharp_call_start_serverside          ModelClassType grpcsharp_call_start_serverside_delegate grpcsharp_call_start_serverside_delegate grpcsharp_call_start_serverside_delegate Pointer
    // 130 Grpcsharp_call_send_initial_metadata     ModelClassType grpcsharp_call_send_initial_metadata_delegate grpcsharp_call_send_initial_metadata_delegate grpcsharp_call_send_initial_metadata_delegate Pointer
    // 138 Grpcsharp_call_set_credentials           ModelClassType grpcsharp_call_set_credentials_delegate grpcsharp_call_set_credentials_delegate grpcsharp_call_set_credentials_delegate Pointer
    // 140 Grpcsharp_call_get_peer                  ModelClassType grpcsharp_call_get_peer_delegate grpcsharp_call_get_peer_delegate grpcsharp_call_get_peer_delegate Pointer
    // 148 Grpcsharp_call_destroy                   ModelClassType grpcsharp_call_destroy_delegate grpcsharp_call_destroy_delegate grpcsharp_call_destroy_delegate Pointer
    // 150 Grpcsharp_channel_args_create            ModelClassType grpcsharp_channel_args_create_delegate grpcsharp_channel_args_create_delegate grpcsharp_channel_args_create_delegate Pointer
    // 158 Grpcsharp_channel_args_set_string        ModelClassType grpcsharp_channel_args_set_string_delegate grpcsharp_channel_args_set_string_delegate grpcsharp_channel_args_set_string_delegate Pointer
    // 160 Grpcsharp_channel_args_set_integer       ModelClassType grpcsharp_channel_args_set_integer_delegate grpcsharp_channel_args_set_integer_delegate grpcsharp_channel_args_set_integer_delegate Pointer
    // 168 Grpcsharp_channel_args_destroy           ModelClassType grpcsharp_channel_args_destroy_delegate grpcsharp_channel_args_destroy_delegate grpcsharp_channel_args_destroy_delegate Pointer
    // 170 Grpcsharp_override_default_ssl_roots     ModelClassType grpcsharp_override_default_ssl_roots_delegate grpcsharp_override_default_ssl_roots_delegate grpcsharp_override_default_ssl_roots_delegate Pointer
    // 178 Grpcsharp_ssl_credentials_create         ModelClassType grpcsharp_ssl_credentials_create_delegate grpcsharp_ssl_credentials_create_delegate grpcsharp_ssl_credentials_create_delegate Pointer
    // 180 Grpcsharp_composite_channel_credentials_create ModelClassType grpcsharp_composite_channel_credentials_create_delegate grpcsharp_composite_channel_credentials_create_delegate grpcsharp_composite_channel_credentials_create_delegate Pointer
    // 188 Grpcsharp_channel_credentials_release    ModelClassType grpcsharp_channel_credentials_release_delegate grpcsharp_channel_credentials_release_delegate grpcsharp_channel_credentials_release_delegate Pointer
    // 190 Grpcsharp_insecure_channel_create        ModelClassType grpcsharp_insecure_channel_create_delegate grpcsharp_insecure_channel_create_delegate grpcsharp_insecure_channel_create_delegate Pointer
    // 198 Grpcsharp_secure_channel_create          ModelClassType grpcsharp_secure_channel_create_delegate grpcsharp_secure_channel_create_delegate grpcsharp_secure_channel_create_delegate Pointer
    // 1A0 Grpcsharp_channel_create_call            ModelClassType grpcsharp_channel_create_call_delegate grpcsharp_channel_create_call_delegate grpcsharp_channel_create_call_delegate Pointer
    // 1A8 Grpcsharp_channel_check_connectivity_state ModelClassType grpcsharp_channel_check_connectivity_state_delegate grpcsharp_channel_check_connectivity_state_delegate grpcsharp_channel_check_connectivity_state_delegate Pointer
    // 1B0 Grpcsharp_channel_watch_connectivity_state ModelClassType grpcsharp_channel_watch_connectivity_state_delegate grpcsharp_channel_watch_connectivity_state_delegate grpcsharp_channel_watch_connectivity_state_delegate Pointer
    // 1B8 Grpcsharp_channel_get_target             ModelClassType grpcsharp_channel_get_target_delegate grpcsharp_channel_get_target_delegate grpcsharp_channel_get_target_delegate Pointer
    // 1C0 Grpcsharp_channel_destroy                ModelClassType grpcsharp_channel_destroy_delegate grpcsharp_channel_destroy_delegate grpcsharp_channel_destroy_delegate Pointer
    // 1C8 Grpcsharp_sizeof_grpc_event              ModelClassType grpcsharp_sizeof_grpc_event_delegate grpcsharp_sizeof_grpc_event_delegate grpcsharp_sizeof_grpc_event_delegate Pointer
    // 1D0 Grpcsharp_completion_queue_create_async  ModelClassType grpcsharp_completion_queue_create_async_delegate grpcsharp_completion_queue_create_async_delegate grpcsharp_completion_queue_create_async_delegate Pointer
    // 1D8 Grpcsharp_completion_queue_create_sync   ModelClassType grpcsharp_completion_queue_create_sync_delegate grpcsharp_completion_queue_create_sync_delegate grpcsharp_completion_queue_create_sync_delegate Pointer
    // 1E0 Grpcsharp_completion_queue_shutdown      ModelClassType grpcsharp_completion_queue_shutdown_delegate grpcsharp_completion_queue_shutdown_delegate grpcsharp_completion_queue_shutdown_delegate Pointer
    // 1E8 Grpcsharp_completion_queue_next          ModelClassType grpcsharp_completion_queue_next_delegate grpcsharp_completion_queue_next_delegate grpcsharp_completion_queue_next_delegate Pointer
    // 1F0 Grpcsharp_completion_queue_pluck         ModelClassType grpcsharp_completion_queue_pluck_delegate grpcsharp_completion_queue_pluck_delegate grpcsharp_completion_queue_pluck_delegate Pointer
    // 1F8 Grpcsharp_completion_queue_destroy       ModelClassType grpcsharp_completion_queue_destroy_delegate grpcsharp_completion_queue_destroy_delegate grpcsharp_completion_queue_destroy_delegate Pointer
    // 200 Gprsharp_free                            ModelClassType gprsharp_free_delegate gprsharp_free_delegate gprsharp_free_delegate Pointer
    // 208 Grpcsharp_metadata_array_create          ModelClassType grpcsharp_metadata_array_create_delegate grpcsharp_metadata_array_create_delegate grpcsharp_metadata_array_create_delegate Pointer
    // 210 Grpcsharp_metadata_array_add             ModelClassType grpcsharp_metadata_array_add_delegate grpcsharp_metadata_array_add_delegate grpcsharp_metadata_array_add_delegate Pointer
    // 218 Grpcsharp_metadata_array_count           ModelClassType grpcsharp_metadata_array_count_delegate grpcsharp_metadata_array_count_delegate grpcsharp_metadata_array_count_delegate Pointer
    // 220 Grpcsharp_metadata_array_get_key         ModelClassType grpcsharp_metadata_array_get_key_delegate grpcsharp_metadata_array_get_key_delegate grpcsharp_metadata_array_get_key_delegate Pointer
    // 228 Grpcsharp_metadata_array_get_value       ModelClassType grpcsharp_metadata_array_get_value_delegate grpcsharp_metadata_array_get_value_delegate grpcsharp_metadata_array_get_value_delegate Pointer
    // 230 Grpcsharp_metadata_array_destroy_full    ModelClassType grpcsharp_metadata_array_destroy_full_delegate grpcsharp_metadata_array_destroy_full_delegate grpcsharp_metadata_array_destroy_full_delegate Pointer
    // 238 Grpcsharp_redirect_log                   ModelClassType grpcsharp_redirect_log_delegate grpcsharp_redirect_log_delegate grpcsharp_redirect_log_delegate Pointer
    // 240 Grpcsharp_native_callback_dispatcher_init ModelClassType grpcsharp_native_callback_dispatcher_init_delegate grpcsharp_native_callback_dispatcher_init_delegate grpcsharp_native_callback_dispatcher_init_delegate Pointer
    // 248 Grpcsharp_metadata_credentials_create_from_plugin ModelClassType grpcsharp_metadata_credentials_create_from_plugin_delegate grpcsharp_metadata_credentials_create_from_plugin_delegate grpcsharp_metadata_credentials_create_from_plugin_delegate Pointer
    // 250 Grpcsharp_metadata_credentials_notify_from_plugin ModelClassType grpcsharp_metadata_credentials_notify_from_plugin_delegate grpcsharp_metadata_credentials_notify_from_plugin_delegate grpcsharp_metadata_credentials_notify_from_plugin_delegate Pointer
    // 258 Grpcsharp_ssl_server_credentials_create  ModelClassType grpcsharp_ssl_server_credentials_create_delegate grpcsharp_ssl_server_credentials_create_delegate grpcsharp_ssl_server_credentials_create_delegate Pointer
    // 260 Grpcsharp_server_credentials_release     ModelClassType grpcsharp_server_credentials_release_delegate grpcsharp_server_credentials_release_delegate grpcsharp_server_credentials_release_delegate Pointer
    // 268 Grpcsharp_server_create                  ModelClassType grpcsharp_server_create_delegate grpcsharp_server_create_delegate grpcsharp_server_create_delegate Pointer
    // 270 Grpcsharp_server_register_completion_queue ModelClassType grpcsharp_server_register_completion_queue_delegate grpcsharp_server_register_completion_queue_delegate grpcsharp_server_register_completion_queue_delegate Pointer
    // 278 Grpcsharp_server_add_insecure_http2_port ModelClassType grpcsharp_server_add_insecure_http2_port_delegate grpcsharp_server_add_insecure_http2_port_delegate grpcsharp_server_add_insecure_http2_port_delegate Pointer
    // 280 Grpcsharp_server_add_secure_http2_port   ModelClassType grpcsharp_server_add_secure_http2_port_delegate grpcsharp_server_add_secure_http2_port_delegate grpcsharp_server_add_secure_http2_port_delegate Pointer
    // 288 Grpcsharp_server_start                   ModelClassType grpcsharp_server_start_delegate grpcsharp_server_start_delegate grpcsharp_server_start_delegate Pointer
    // 290 Grpcsharp_server_request_call            ModelClassType grpcsharp_server_request_call_delegate grpcsharp_server_request_call_delegate grpcsharp_server_request_call_delegate Pointer
    // 298 Grpcsharp_server_cancel_all_calls        ModelClassType grpcsharp_server_cancel_all_calls_delegate grpcsharp_server_cancel_all_calls_delegate grpcsharp_server_cancel_all_calls_delegate Pointer
    // 2A0 Grpcsharp_server_shutdown_and_notify_callback ModelClassType grpcsharp_server_shutdown_and_notify_callback_delegate grpcsharp_server_shutdown_and_notify_callback_delegate grpcsharp_server_shutdown_and_notify_callback_delegate Pointer
    // 2A8 Grpcsharp_server_destroy                 ModelClassType grpcsharp_server_destroy_delegate grpcsharp_server_destroy_delegate grpcsharp_server_destroy_delegate Pointer
    // 2B0 Grpcsharp_call_auth_context              ModelClassType grpcsharp_call_auth_context_delegate grpcsharp_call_auth_context_delegate grpcsharp_call_auth_context_delegate Pointer
    // 2B8 Grpcsharp_auth_context_peer_identity_property_name ModelClassType grpcsharp_auth_context_peer_identity_property_name_delegate grpcsharp_auth_context_peer_identity_property_name_delegate grpcsharp_auth_context_peer_identity_property_name_delegate Pointer
    // 2C0 Grpcsharp_auth_context_property_iterator ModelClassType grpcsharp_auth_context_property_iterator_delegate grpcsharp_auth_context_property_iterator_delegate grpcsharp_auth_context_property_iterator_delegate Pointer
    // 2C8 Grpcsharp_auth_property_iterator_next    ModelClassType grpcsharp_auth_property_iterator_next_delegate grpcsharp_auth_property_iterator_next_delegate grpcsharp_auth_property_iterator_next_delegate Pointer
    // 2D0 Grpcsharp_auth_context_release           ModelClassType grpcsharp_auth_context_release_delegate grpcsharp_auth_context_release_delegate grpcsharp_auth_context_release_delegate Pointer
    // 2D8 Grpcsharp_slice_buffer_create            ModelClassType grpcsharp_slice_buffer_create_delegate grpcsharp_slice_buffer_create_delegate grpcsharp_slice_buffer_create_delegate Pointer
    // 2E0 Grpcsharp_slice_buffer_adjust_tail_space ModelClassType grpcsharp_slice_buffer_adjust_tail_space_delegate grpcsharp_slice_buffer_adjust_tail_space_delegate grpcsharp_slice_buffer_adjust_tail_space_delegate Pointer
    // 2E8 Grpcsharp_slice_buffer_slice_count       ModelClassType grpcsharp_slice_buffer_slice_count_delegate grpcsharp_slice_buffer_slice_count_delegate grpcsharp_slice_buffer_slice_count_delegate Pointer
    // 2F0 Grpcsharp_slice_buffer_slice_peek        ModelClassType grpcsharp_slice_buffer_slice_peek_delegate grpcsharp_slice_buffer_slice_peek_delegate grpcsharp_slice_buffer_slice_peek_delegate Pointer
    // 2F8 Grpcsharp_slice_buffer_reset_and_unref   ModelClassType grpcsharp_slice_buffer_reset_and_unref_delegate grpcsharp_slice_buffer_reset_and_unref_delegate grpcsharp_slice_buffer_reset_and_unref_delegate Pointer
    // 300 Grpcsharp_slice_buffer_destroy           ModelClassType grpcsharp_slice_buffer_destroy_delegate grpcsharp_slice_buffer_destroy_delegate grpcsharp_slice_buffer_destroy_delegate Pointer
    // 308 Gprsharp_now                             ModelClassType gprsharp_now_delegate gprsharp_now_delegate gprsharp_now_delegate Pointer
    // 310 Gprsharp_inf_future                      ModelClassType gprsharp_inf_future_delegate gprsharp_inf_future_delegate gprsharp_inf_future_delegate Pointer
    // 318 Gprsharp_inf_past                        ModelClassType gprsharp_inf_past_delegate gprsharp_inf_past_delegate gprsharp_inf_past_delegate Pointer
    // 320 Gprsharp_convert_clock_type              ModelClassType gprsharp_convert_clock_type_delegate gprsharp_convert_clock_type_delegate gprsharp_convert_clock_type_delegate Pointer
    // 328 Gprsharp_sizeof_timespec                 ModelClassType gprsharp_sizeof_timespec_delegate gprsharp_sizeof_timespec_delegate gprsharp_sizeof_timespec_delegate Pointer
    // 330 Grpcsharp_test_callback                  ModelClassType grpcsharp_test_callback_delegate grpcsharp_test_callback_delegate grpcsharp_test_callback_delegate Pointer
    // 338 Grpcsharp_test_nop                       ModelClassType grpcsharp_test_nop_delegate grpcsharp_test_nop_delegate grpcsharp_test_nop_delegate Pointer
    // 340 Grpcsharp_test_override_method           ModelClassType grpcsharp_test_override_method_delegate grpcsharp_test_override_method_delegate grpcsharp_test_override_method_delegate Pointer
    // 348 Grpcsharp_test_call_start_unary_echo     ModelClassType grpcsharp_test_call_start_unary_echo_delegate grpcsharp_test_call_start_unary_echo_delegate grpcsharp_test_call_start_unary_echo_delegate Pointer
    public partial class NativeMethods : DataModel
    {
        public grpcsharp_init_delegate?                 Grpcsharp_init                          { get; set; }
        public grpcsharp_shutdown_delegate?             Grpcsharp_shutdown                      { get; set; }
        public grpcsharp_version_string_delegate?       Grpcsharp_version_string                { get; set; }
        public grpcsharp_batch_context_create_delegate? Grpcsharp_batch_context_create          { get; set; }
        public grpcsharp_batch_context_recv_initial_metadata_delegate? Grpcsharp_batch_context_recv_initial_metadata { get; set; }
        public grpcsharp_batch_context_recv_message_length_delegate? Grpcsharp_batch_context_recv_message_length { get; set; }
        public grpcsharp_batch_context_recv_message_next_slice_peek_delegate? Grpcsharp_batch_context_recv_message_next_slice_peek { get; set; }
        public grpcsharp_batch_context_recv_status_on_client_status_delegate? Grpcsharp_batch_context_recv_status_on_client_status { get; set; }
        public grpcsharp_batch_context_recv_status_on_client_details_delegate? Grpcsharp_batch_context_recv_status_on_client_details { get; set; }
        public grpcsharp_batch_context_recv_status_on_client_error_string_delegate? Grpcsharp_batch_context_recv_status_on_client_error_string { get; set; }
        public grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate? Grpcsharp_batch_context_recv_status_on_client_trailing_metadata { get; set; }
        public grpcsharp_batch_context_recv_close_on_server_cancelled_delegate? Grpcsharp_batch_context_recv_close_on_server_cancelled { get; set; }
        public grpcsharp_batch_context_reset_delegate?  Grpcsharp_batch_context_reset           { get; set; }
        public grpcsharp_batch_context_destroy_delegate? Grpcsharp_batch_context_destroy         { get; set; }
        public grpcsharp_request_call_context_create_delegate? Grpcsharp_request_call_context_create   { get; set; }
        public grpcsharp_request_call_context_call_delegate? Grpcsharp_request_call_context_call     { get; set; }
        public grpcsharp_request_call_context_method_delegate? Grpcsharp_request_call_context_method   { get; set; }
        public grpcsharp_request_call_context_host_delegate? Grpcsharp_request_call_context_host     { get; set; }
        public grpcsharp_request_call_context_deadline_delegate? Grpcsharp_request_call_context_deadline { get; set; }
        public grpcsharp_request_call_context_request_metadata_delegate? Grpcsharp_request_call_context_request_metadata { get; set; }
        public grpcsharp_request_call_context_reset_delegate? Grpcsharp_request_call_context_reset    { get; set; }
        public grpcsharp_request_call_context_destroy_delegate? Grpcsharp_request_call_context_destroy  { get; set; }
        public grpcsharp_composite_call_credentials_create_delegate? Grpcsharp_composite_call_credentials_create { get; set; }
        public grpcsharp_call_credentials_release_delegate? Grpcsharp_call_credentials_release      { get; set; }
        public grpcsharp_call_cancel_delegate?          Grpcsharp_call_cancel                   { get; set; }
        public grpcsharp_call_cancel_with_status_delegate? Grpcsharp_call_cancel_with_status       { get; set; }
        public grpcsharp_call_start_unary_delegate?     Grpcsharp_call_start_unary              { get; set; }
        public grpcsharp_call_start_client_streaming_delegate? Grpcsharp_call_start_client_streaming   { get; set; }
        public grpcsharp_call_start_server_streaming_delegate? Grpcsharp_call_start_server_streaming   { get; set; }
        public grpcsharp_call_start_duplex_streaming_delegate? Grpcsharp_call_start_duplex_streaming   { get; set; }
        public grpcsharp_call_send_message_delegate?    Grpcsharp_call_send_message             { get; set; }
        public grpcsharp_call_send_close_from_client_delegate? Grpcsharp_call_send_close_from_client   { get; set; }
        public grpcsharp_call_send_status_from_server_delegate? Grpcsharp_call_send_status_from_server  { get; set; }
        public grpcsharp_call_recv_message_delegate?    Grpcsharp_call_recv_message             { get; set; }
        public grpcsharp_call_recv_initial_metadata_delegate? Grpcsharp_call_recv_initial_metadata    { get; set; }
        public grpcsharp_call_start_serverside_delegate? Grpcsharp_call_start_serverside         { get; set; }
        public grpcsharp_call_send_initial_metadata_delegate? Grpcsharp_call_send_initial_metadata    { get; set; }
        public grpcsharp_call_set_credentials_delegate? Grpcsharp_call_set_credentials          { get; set; }
        public grpcsharp_call_get_peer_delegate?        Grpcsharp_call_get_peer                 { get; set; }
        public grpcsharp_call_destroy_delegate?         Grpcsharp_call_destroy                  { get; set; }
        public grpcsharp_channel_args_create_delegate?  Grpcsharp_channel_args_create           { get; set; }
        public grpcsharp_channel_args_set_string_delegate? Grpcsharp_channel_args_set_string       { get; set; }
        public grpcsharp_channel_args_set_integer_delegate? Grpcsharp_channel_args_set_integer      { get; set; }
        public grpcsharp_channel_args_destroy_delegate? Grpcsharp_channel_args_destroy          { get; set; }
        public grpcsharp_override_default_ssl_roots_delegate? Grpcsharp_override_default_ssl_roots    { get; set; }
        public grpcsharp_ssl_credentials_create_delegate? Grpcsharp_ssl_credentials_create        { get; set; }
        public grpcsharp_composite_channel_credentials_create_delegate? Grpcsharp_composite_channel_credentials_create { get; set; }
        public grpcsharp_channel_credentials_release_delegate? Grpcsharp_channel_credentials_release   { get; set; }
        public grpcsharp_insecure_channel_create_delegate? Grpcsharp_insecure_channel_create       { get; set; }
        public grpcsharp_secure_channel_create_delegate? Grpcsharp_secure_channel_create         { get; set; }
        public grpcsharp_channel_create_call_delegate?  Grpcsharp_channel_create_call           { get; set; }
        public grpcsharp_channel_check_connectivity_state_delegate? Grpcsharp_channel_check_connectivity_state { get; set; }
        public grpcsharp_channel_watch_connectivity_state_delegate? Grpcsharp_channel_watch_connectivity_state { get; set; }
        public grpcsharp_channel_get_target_delegate?   Grpcsharp_channel_get_target            { get; set; }
        public grpcsharp_channel_destroy_delegate?      Grpcsharp_channel_destroy               { get; set; }
        public grpcsharp_sizeof_grpc_event_delegate?    Grpcsharp_sizeof_grpc_event             { get; set; }
        public grpcsharp_completion_queue_create_async_delegate? Grpcsharp_completion_queue_create_async { get; set; }
        public grpcsharp_completion_queue_create_sync_delegate? Grpcsharp_completion_queue_create_sync  { get; set; }
        public grpcsharp_completion_queue_shutdown_delegate? Grpcsharp_completion_queue_shutdown     { get; set; }
        public grpcsharp_completion_queue_next_delegate? Grpcsharp_completion_queue_next         { get; set; }
        public grpcsharp_completion_queue_pluck_delegate? Grpcsharp_completion_queue_pluck        { get; set; }
        public grpcsharp_completion_queue_destroy_delegate? Grpcsharp_completion_queue_destroy      { get; set; }
        public gprsharp_free_delegate?                  Gprsharp_free                           { get; set; }
        public grpcsharp_metadata_array_create_delegate? Grpcsharp_metadata_array_create         { get; set; }
        public grpcsharp_metadata_array_add_delegate?   Grpcsharp_metadata_array_add            { get; set; }
        public grpcsharp_metadata_array_count_delegate? Grpcsharp_metadata_array_count          { get; set; }
        public grpcsharp_metadata_array_get_key_delegate? Grpcsharp_metadata_array_get_key        { get; set; }
        public grpcsharp_metadata_array_get_value_delegate? Grpcsharp_metadata_array_get_value      { get; set; }
        public grpcsharp_metadata_array_destroy_full_delegate? Grpcsharp_metadata_array_destroy_full   { get; set; }
        public grpcsharp_redirect_log_delegate?         Grpcsharp_redirect_log                  { get; set; }
        public grpcsharp_native_callback_dispatcher_init_delegate? Grpcsharp_native_callback_dispatcher_init { get; set; }
        public grpcsharp_metadata_credentials_create_from_plugin_delegate? Grpcsharp_metadata_credentials_create_from_plugin { get; set; }
        public grpcsharp_metadata_credentials_notify_from_plugin_delegate? Grpcsharp_metadata_credentials_notify_from_plugin { get; set; }
        public grpcsharp_ssl_server_credentials_create_delegate? Grpcsharp_ssl_server_credentials_create { get; set; }
        public grpcsharp_server_credentials_release_delegate? Grpcsharp_server_credentials_release    { get; set; }
        public grpcsharp_server_create_delegate?        Grpcsharp_server_create                 { get; set; }
        public grpcsharp_server_register_completion_queue_delegate? Grpcsharp_server_register_completion_queue { get; set; }
        public grpcsharp_server_add_insecure_http2_port_delegate? Grpcsharp_server_add_insecure_http2_port { get; set; }
        public grpcsharp_server_add_secure_http2_port_delegate? Grpcsharp_server_add_secure_http2_port  { get; set; }
        public grpcsharp_server_start_delegate?         Grpcsharp_server_start                  { get; set; }
        public grpcsharp_server_request_call_delegate?  Grpcsharp_server_request_call           { get; set; }
        public grpcsharp_server_cancel_all_calls_delegate? Grpcsharp_server_cancel_all_calls       { get; set; }
        public grpcsharp_server_shutdown_and_notify_callback_delegate? Grpcsharp_server_shutdown_and_notify_callback { get; set; }
        public grpcsharp_server_destroy_delegate?       Grpcsharp_server_destroy                { get; set; }
        public grpcsharp_call_auth_context_delegate?    Grpcsharp_call_auth_context             { get; set; }
        public grpcsharp_auth_context_peer_identity_property_name_delegate? Grpcsharp_auth_context_peer_identity_property_name { get; set; }
        public grpcsharp_auth_context_property_iterator_delegate? Grpcsharp_auth_context_property_iterator { get; set; }
        public grpcsharp_auth_property_iterator_next_delegate? Grpcsharp_auth_property_iterator_next   { get; set; }
        public grpcsharp_auth_context_release_delegate? Grpcsharp_auth_context_release          { get; set; }
        public grpcsharp_slice_buffer_create_delegate?  Grpcsharp_slice_buffer_create           { get; set; }
        public grpcsharp_slice_buffer_adjust_tail_space_delegate? Grpcsharp_slice_buffer_adjust_tail_space { get; set; }
        public grpcsharp_slice_buffer_slice_count_delegate? Grpcsharp_slice_buffer_slice_count      { get; set; }
        public grpcsharp_slice_buffer_slice_peek_delegate? Grpcsharp_slice_buffer_slice_peek       { get; set; }
        public grpcsharp_slice_buffer_reset_and_unref_delegate? Grpcsharp_slice_buffer_reset_and_unref  { get; set; }
        public grpcsharp_slice_buffer_destroy_delegate? Grpcsharp_slice_buffer_destroy          { get; set; }
        public gprsharp_now_delegate?                   Gprsharp_now                            { get; set; }
        public gprsharp_inf_future_delegate?            Gprsharp_inf_future                     { get; set; }
        public gprsharp_inf_past_delegate?              Gprsharp_inf_past                       { get; set; }
        public gprsharp_convert_clock_type_delegate?    Gprsharp_convert_clock_type             { get; set; }
        public gprsharp_sizeof_timespec_delegate?       Gprsharp_sizeof_timespec                { get; set; }
        public grpcsharp_test_callback_delegate?        Grpcsharp_test_callback                 { get; set; }
        public grpcsharp_test_nop_delegate?             Grpcsharp_test_nop                      { get; set; }
        public grpcsharp_test_override_method_delegate? Grpcsharp_test_override_method          { get; set; }
        public grpcsharp_test_call_start_unary_echo_delegate? Grpcsharp_test_call_start_unary_echo    { get; set; }

        public static NativeMethods? FromPointer(IntPtr p0)
        {
            if(p0 == IntPtr.Zero)
                return null;

            var p       = p0.ToInt64();
            var value   = new NativeMethods() { Pointer= p0 };

            value.Grpcsharp_init                            = GetObject<grpcsharp_init_delegate>(new IntPtr(p + 0x010), ReversePrism.DataModels.grpcsharp_init_delegate.FromPointer); // 0x10 Grpcsharp_init              ( ModelClassType grpcsharp_init_delegate grpcsharp_init_delegate grpcsharp_init_delegate Pointer )
            value.Grpcsharp_shutdown                        = GetObject<grpcsharp_shutdown_delegate>(new IntPtr(p + 0x018), ReversePrism.DataModels.grpcsharp_shutdown_delegate.FromPointer); // 0x18 Grpcsharp_shutdown          ( ModelClassType grpcsharp_shutdown_delegate grpcsharp_shutdown_delegate grpcsharp_shutdown_delegate Pointer )
            value.Grpcsharp_version_string                  = GetObject<grpcsharp_version_string_delegate>(new IntPtr(p + 0x020), ReversePrism.DataModels.grpcsharp_version_string_delegate.FromPointer); // 0x20 Grpcsharp_version_string    ( ModelClassType grpcsharp_version_string_delegate grpcsharp_version_string_delegate grpcsharp_version_string_delegate Pointer )
            value.Grpcsharp_batch_context_create            = GetObject<grpcsharp_batch_context_create_delegate>(new IntPtr(p + 0x028), ReversePrism.DataModels.grpcsharp_batch_context_create_delegate.FromPointer); // 0x28 Grpcsharp_batch_context_create ( ModelClassType grpcsharp_batch_context_create_delegate grpcsharp_batch_context_create_delegate grpcsharp_batch_context_create_delegate Pointer )
            value.Grpcsharp_batch_context_recv_initial_metadata = GetObject<grpcsharp_batch_context_recv_initial_metadata_delegate>(new IntPtr(p + 0x030), ReversePrism.DataModels.grpcsharp_batch_context_recv_initial_metadata_delegate.FromPointer); // 0x30 Grpcsharp_batch_context_recv_initial_metadata ( ModelClassType grpcsharp_batch_context_recv_initial_metadata_delegate grpcsharp_batch_context_recv_initial_metadata_delegate grpcsharp_batch_context_recv_initial_metadata_delegate Pointer )
            value.Grpcsharp_batch_context_recv_message_length = GetObject<grpcsharp_batch_context_recv_message_length_delegate>(new IntPtr(p + 0x038), ReversePrism.DataModels.grpcsharp_batch_context_recv_message_length_delegate.FromPointer); // 0x38 Grpcsharp_batch_context_recv_message_length ( ModelClassType grpcsharp_batch_context_recv_message_length_delegate grpcsharp_batch_context_recv_message_length_delegate grpcsharp_batch_context_recv_message_length_delegate Pointer )
            value.Grpcsharp_batch_context_recv_message_next_slice_peek = GetObject<grpcsharp_batch_context_recv_message_next_slice_peek_delegate>(new IntPtr(p + 0x040), ReversePrism.DataModels.grpcsharp_batch_context_recv_message_next_slice_peek_delegate.FromPointer); // 0x40 Grpcsharp_batch_context_recv_message_next_slice_peek ( ModelClassType grpcsharp_batch_context_recv_message_next_slice_peek_delegate grpcsharp_batch_context_recv_message_next_slice_peek_delegate grpcsharp_batch_context_recv_message_next_slice_peek_delegate Pointer )
            value.Grpcsharp_batch_context_recv_status_on_client_status = GetObject<grpcsharp_batch_context_recv_status_on_client_status_delegate>(new IntPtr(p + 0x048), ReversePrism.DataModels.grpcsharp_batch_context_recv_status_on_client_status_delegate.FromPointer); // 0x48 Grpcsharp_batch_context_recv_status_on_client_status ( ModelClassType grpcsharp_batch_context_recv_status_on_client_status_delegate grpcsharp_batch_context_recv_status_on_client_status_delegate grpcsharp_batch_context_recv_status_on_client_status_delegate Pointer )
            value.Grpcsharp_batch_context_recv_status_on_client_details = GetObject<grpcsharp_batch_context_recv_status_on_client_details_delegate>(new IntPtr(p + 0x050), ReversePrism.DataModels.grpcsharp_batch_context_recv_status_on_client_details_delegate.FromPointer); // 0x50 Grpcsharp_batch_context_recv_status_on_client_details ( ModelClassType grpcsharp_batch_context_recv_status_on_client_details_delegate grpcsharp_batch_context_recv_status_on_client_details_delegate grpcsharp_batch_context_recv_status_on_client_details_delegate Pointer )
            value.Grpcsharp_batch_context_recv_status_on_client_error_string = GetObject<grpcsharp_batch_context_recv_status_on_client_error_string_delegate>(new IntPtr(p + 0x058), ReversePrism.DataModels.grpcsharp_batch_context_recv_status_on_client_error_string_delegate.FromPointer); // 0x58 Grpcsharp_batch_context_recv_status_on_client_error_string ( ModelClassType grpcsharp_batch_context_recv_status_on_client_error_string_delegate grpcsharp_batch_context_recv_status_on_client_error_string_delegate grpcsharp_batch_context_recv_status_on_client_error_string_delegate Pointer )
            value.Grpcsharp_batch_context_recv_status_on_client_trailing_metadata = GetObject<grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate>(new IntPtr(p + 0x060), ReversePrism.DataModels.grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate.FromPointer); // 0x60 Grpcsharp_batch_context_recv_status_on_client_trailing_metadata ( ModelClassType grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate grpcsharp_batch_context_recv_status_on_client_trailing_metadata_delegate Pointer )
            value.Grpcsharp_batch_context_recv_close_on_server_cancelled = GetObject<grpcsharp_batch_context_recv_close_on_server_cancelled_delegate>(new IntPtr(p + 0x068), ReversePrism.DataModels.grpcsharp_batch_context_recv_close_on_server_cancelled_delegate.FromPointer); // 0x68 Grpcsharp_batch_context_recv_close_on_server_cancelled ( ModelClassType grpcsharp_batch_context_recv_close_on_server_cancelled_delegate grpcsharp_batch_context_recv_close_on_server_cancelled_delegate grpcsharp_batch_context_recv_close_on_server_cancelled_delegate Pointer )
            value.Grpcsharp_batch_context_reset             = GetObject<grpcsharp_batch_context_reset_delegate>(new IntPtr(p + 0x070), ReversePrism.DataModels.grpcsharp_batch_context_reset_delegate.FromPointer); // 0x70 Grpcsharp_batch_context_reset ( ModelClassType grpcsharp_batch_context_reset_delegate grpcsharp_batch_context_reset_delegate grpcsharp_batch_context_reset_delegate Pointer )
            value.Grpcsharp_batch_context_destroy           = GetObject<grpcsharp_batch_context_destroy_delegate>(new IntPtr(p + 0x078), ReversePrism.DataModels.grpcsharp_batch_context_destroy_delegate.FromPointer); // 0x78 Grpcsharp_batch_context_destroy ( ModelClassType grpcsharp_batch_context_destroy_delegate grpcsharp_batch_context_destroy_delegate grpcsharp_batch_context_destroy_delegate Pointer )
            value.Grpcsharp_request_call_context_create     = GetObject<grpcsharp_request_call_context_create_delegate>(new IntPtr(p + 0x080), ReversePrism.DataModels.grpcsharp_request_call_context_create_delegate.FromPointer); // 0x80 Grpcsharp_request_call_context_create ( ModelClassType grpcsharp_request_call_context_create_delegate grpcsharp_request_call_context_create_delegate grpcsharp_request_call_context_create_delegate Pointer )
            value.Grpcsharp_request_call_context_call       = GetObject<grpcsharp_request_call_context_call_delegate>(new IntPtr(p + 0x088), ReversePrism.DataModels.grpcsharp_request_call_context_call_delegate.FromPointer); // 0x88 Grpcsharp_request_call_context_call ( ModelClassType grpcsharp_request_call_context_call_delegate grpcsharp_request_call_context_call_delegate grpcsharp_request_call_context_call_delegate Pointer )
            value.Grpcsharp_request_call_context_method     = GetObject<grpcsharp_request_call_context_method_delegate>(new IntPtr(p + 0x090), ReversePrism.DataModels.grpcsharp_request_call_context_method_delegate.FromPointer); // 0x90 Grpcsharp_request_call_context_method ( ModelClassType grpcsharp_request_call_context_method_delegate grpcsharp_request_call_context_method_delegate grpcsharp_request_call_context_method_delegate Pointer )
            value.Grpcsharp_request_call_context_host       = GetObject<grpcsharp_request_call_context_host_delegate>(new IntPtr(p + 0x098), ReversePrism.DataModels.grpcsharp_request_call_context_host_delegate.FromPointer); // 0x98 Grpcsharp_request_call_context_host ( ModelClassType grpcsharp_request_call_context_host_delegate grpcsharp_request_call_context_host_delegate grpcsharp_request_call_context_host_delegate Pointer )
            value.Grpcsharp_request_call_context_deadline   = GetObject<grpcsharp_request_call_context_deadline_delegate>(new IntPtr(p + 0x0A0), ReversePrism.DataModels.grpcsharp_request_call_context_deadline_delegate.FromPointer); // 0xA0 Grpcsharp_request_call_context_deadline ( ModelClassType grpcsharp_request_call_context_deadline_delegate grpcsharp_request_call_context_deadline_delegate grpcsharp_request_call_context_deadline_delegate Pointer )
            value.Grpcsharp_request_call_context_request_metadata = GetObject<grpcsharp_request_call_context_request_metadata_delegate>(new IntPtr(p + 0x0A8), ReversePrism.DataModels.grpcsharp_request_call_context_request_metadata_delegate.FromPointer); // 0xA8 Grpcsharp_request_call_context_request_metadata ( ModelClassType grpcsharp_request_call_context_request_metadata_delegate grpcsharp_request_call_context_request_metadata_delegate grpcsharp_request_call_context_request_metadata_delegate Pointer )
            value.Grpcsharp_request_call_context_reset      = GetObject<grpcsharp_request_call_context_reset_delegate>(new IntPtr(p + 0x0B0), ReversePrism.DataModels.grpcsharp_request_call_context_reset_delegate.FromPointer); // 0xB0 Grpcsharp_request_call_context_reset ( ModelClassType grpcsharp_request_call_context_reset_delegate grpcsharp_request_call_context_reset_delegate grpcsharp_request_call_context_reset_delegate Pointer )
            value.Grpcsharp_request_call_context_destroy    = GetObject<grpcsharp_request_call_context_destroy_delegate>(new IntPtr(p + 0x0B8), ReversePrism.DataModels.grpcsharp_request_call_context_destroy_delegate.FromPointer); // 0xB8 Grpcsharp_request_call_context_destroy ( ModelClassType grpcsharp_request_call_context_destroy_delegate grpcsharp_request_call_context_destroy_delegate grpcsharp_request_call_context_destroy_delegate Pointer )
            value.Grpcsharp_composite_call_credentials_create = GetObject<grpcsharp_composite_call_credentials_create_delegate>(new IntPtr(p + 0x0C0), ReversePrism.DataModels.grpcsharp_composite_call_credentials_create_delegate.FromPointer); // 0xC0 Grpcsharp_composite_call_credentials_create ( ModelClassType grpcsharp_composite_call_credentials_create_delegate grpcsharp_composite_call_credentials_create_delegate grpcsharp_composite_call_credentials_create_delegate Pointer )
            value.Grpcsharp_call_credentials_release        = GetObject<grpcsharp_call_credentials_release_delegate>(new IntPtr(p + 0x0C8), ReversePrism.DataModels.grpcsharp_call_credentials_release_delegate.FromPointer); // 0xC8 Grpcsharp_call_credentials_release ( ModelClassType grpcsharp_call_credentials_release_delegate grpcsharp_call_credentials_release_delegate grpcsharp_call_credentials_release_delegate Pointer )
            value.Grpcsharp_call_cancel                     = GetObject<grpcsharp_call_cancel_delegate>(new IntPtr(p + 0x0D0), ReversePrism.DataModels.grpcsharp_call_cancel_delegate.FromPointer); // 0xD0 Grpcsharp_call_cancel       ( ModelClassType grpcsharp_call_cancel_delegate grpcsharp_call_cancel_delegate grpcsharp_call_cancel_delegate Pointer )
            value.Grpcsharp_call_cancel_with_status         = GetObject<grpcsharp_call_cancel_with_status_delegate>(new IntPtr(p + 0x0D8), ReversePrism.DataModels.grpcsharp_call_cancel_with_status_delegate.FromPointer); // 0xD8 Grpcsharp_call_cancel_with_status ( ModelClassType grpcsharp_call_cancel_with_status_delegate grpcsharp_call_cancel_with_status_delegate grpcsharp_call_cancel_with_status_delegate Pointer )
            value.Grpcsharp_call_start_unary                = GetObject<grpcsharp_call_start_unary_delegate>(new IntPtr(p + 0x0E0), ReversePrism.DataModels.grpcsharp_call_start_unary_delegate.FromPointer); // 0xE0 Grpcsharp_call_start_unary  ( ModelClassType grpcsharp_call_start_unary_delegate grpcsharp_call_start_unary_delegate grpcsharp_call_start_unary_delegate Pointer )
            value.Grpcsharp_call_start_client_streaming     = GetObject<grpcsharp_call_start_client_streaming_delegate>(new IntPtr(p + 0x0E8), ReversePrism.DataModels.grpcsharp_call_start_client_streaming_delegate.FromPointer); // 0xE8 Grpcsharp_call_start_client_streaming ( ModelClassType grpcsharp_call_start_client_streaming_delegate grpcsharp_call_start_client_streaming_delegate grpcsharp_call_start_client_streaming_delegate Pointer )
            value.Grpcsharp_call_start_server_streaming     = GetObject<grpcsharp_call_start_server_streaming_delegate>(new IntPtr(p + 0x0F0), ReversePrism.DataModels.grpcsharp_call_start_server_streaming_delegate.FromPointer); // 0xF0 Grpcsharp_call_start_server_streaming ( ModelClassType grpcsharp_call_start_server_streaming_delegate grpcsharp_call_start_server_streaming_delegate grpcsharp_call_start_server_streaming_delegate Pointer )
            value.Grpcsharp_call_start_duplex_streaming     = GetObject<grpcsharp_call_start_duplex_streaming_delegate>(new IntPtr(p + 0x0F8), ReversePrism.DataModels.grpcsharp_call_start_duplex_streaming_delegate.FromPointer); // 0xF8 Grpcsharp_call_start_duplex_streaming ( ModelClassType grpcsharp_call_start_duplex_streaming_delegate grpcsharp_call_start_duplex_streaming_delegate grpcsharp_call_start_duplex_streaming_delegate Pointer )
            value.Grpcsharp_call_send_message               = GetObject<grpcsharp_call_send_message_delegate>(new IntPtr(p + 0x100), ReversePrism.DataModels.grpcsharp_call_send_message_delegate.FromPointer); // 0x100 Grpcsharp_call_send_message ( ModelClassType grpcsharp_call_send_message_delegate grpcsharp_call_send_message_delegate grpcsharp_call_send_message_delegate Pointer )
            value.Grpcsharp_call_send_close_from_client     = GetObject<grpcsharp_call_send_close_from_client_delegate>(new IntPtr(p + 0x108), ReversePrism.DataModels.grpcsharp_call_send_close_from_client_delegate.FromPointer); // 0x108 Grpcsharp_call_send_close_from_client ( ModelClassType grpcsharp_call_send_close_from_client_delegate grpcsharp_call_send_close_from_client_delegate grpcsharp_call_send_close_from_client_delegate Pointer )
            value.Grpcsharp_call_send_status_from_server    = GetObject<grpcsharp_call_send_status_from_server_delegate>(new IntPtr(p + 0x110), ReversePrism.DataModels.grpcsharp_call_send_status_from_server_delegate.FromPointer); // 0x110 Grpcsharp_call_send_status_from_server ( ModelClassType grpcsharp_call_send_status_from_server_delegate grpcsharp_call_send_status_from_server_delegate grpcsharp_call_send_status_from_server_delegate Pointer )
            value.Grpcsharp_call_recv_message               = GetObject<grpcsharp_call_recv_message_delegate>(new IntPtr(p + 0x118), ReversePrism.DataModels.grpcsharp_call_recv_message_delegate.FromPointer); // 0x118 Grpcsharp_call_recv_message ( ModelClassType grpcsharp_call_recv_message_delegate grpcsharp_call_recv_message_delegate grpcsharp_call_recv_message_delegate Pointer )
            value.Grpcsharp_call_recv_initial_metadata      = GetObject<grpcsharp_call_recv_initial_metadata_delegate>(new IntPtr(p + 0x120), ReversePrism.DataModels.grpcsharp_call_recv_initial_metadata_delegate.FromPointer); // 0x120 Grpcsharp_call_recv_initial_metadata ( ModelClassType grpcsharp_call_recv_initial_metadata_delegate grpcsharp_call_recv_initial_metadata_delegate grpcsharp_call_recv_initial_metadata_delegate Pointer )
            value.Grpcsharp_call_start_serverside           = GetObject<grpcsharp_call_start_serverside_delegate>(new IntPtr(p + 0x128), ReversePrism.DataModels.grpcsharp_call_start_serverside_delegate.FromPointer); // 0x128 Grpcsharp_call_start_serverside ( ModelClassType grpcsharp_call_start_serverside_delegate grpcsharp_call_start_serverside_delegate grpcsharp_call_start_serverside_delegate Pointer )
            value.Grpcsharp_call_send_initial_metadata      = GetObject<grpcsharp_call_send_initial_metadata_delegate>(new IntPtr(p + 0x130), ReversePrism.DataModels.grpcsharp_call_send_initial_metadata_delegate.FromPointer); // 0x130 Grpcsharp_call_send_initial_metadata ( ModelClassType grpcsharp_call_send_initial_metadata_delegate grpcsharp_call_send_initial_metadata_delegate grpcsharp_call_send_initial_metadata_delegate Pointer )
            value.Grpcsharp_call_set_credentials            = GetObject<grpcsharp_call_set_credentials_delegate>(new IntPtr(p + 0x138), ReversePrism.DataModels.grpcsharp_call_set_credentials_delegate.FromPointer); // 0x138 Grpcsharp_call_set_credentials ( ModelClassType grpcsharp_call_set_credentials_delegate grpcsharp_call_set_credentials_delegate grpcsharp_call_set_credentials_delegate Pointer )
            value.Grpcsharp_call_get_peer                   = GetObject<grpcsharp_call_get_peer_delegate>(new IntPtr(p + 0x140), ReversePrism.DataModels.grpcsharp_call_get_peer_delegate.FromPointer); // 0x140 Grpcsharp_call_get_peer     ( ModelClassType grpcsharp_call_get_peer_delegate grpcsharp_call_get_peer_delegate grpcsharp_call_get_peer_delegate Pointer )
            value.Grpcsharp_call_destroy                    = GetObject<grpcsharp_call_destroy_delegate>(new IntPtr(p + 0x148), ReversePrism.DataModels.grpcsharp_call_destroy_delegate.FromPointer); // 0x148 Grpcsharp_call_destroy      ( ModelClassType grpcsharp_call_destroy_delegate grpcsharp_call_destroy_delegate grpcsharp_call_destroy_delegate Pointer )
            value.Grpcsharp_channel_args_create             = GetObject<grpcsharp_channel_args_create_delegate>(new IntPtr(p + 0x150), ReversePrism.DataModels.grpcsharp_channel_args_create_delegate.FromPointer); // 0x150 Grpcsharp_channel_args_create ( ModelClassType grpcsharp_channel_args_create_delegate grpcsharp_channel_args_create_delegate grpcsharp_channel_args_create_delegate Pointer )
            value.Grpcsharp_channel_args_set_string         = GetObject<grpcsharp_channel_args_set_string_delegate>(new IntPtr(p + 0x158), ReversePrism.DataModels.grpcsharp_channel_args_set_string_delegate.FromPointer); // 0x158 Grpcsharp_channel_args_set_string ( ModelClassType grpcsharp_channel_args_set_string_delegate grpcsharp_channel_args_set_string_delegate grpcsharp_channel_args_set_string_delegate Pointer )
            value.Grpcsharp_channel_args_set_integer        = GetObject<grpcsharp_channel_args_set_integer_delegate>(new IntPtr(p + 0x160), ReversePrism.DataModels.grpcsharp_channel_args_set_integer_delegate.FromPointer); // 0x160 Grpcsharp_channel_args_set_integer ( ModelClassType grpcsharp_channel_args_set_integer_delegate grpcsharp_channel_args_set_integer_delegate grpcsharp_channel_args_set_integer_delegate Pointer )
            value.Grpcsharp_channel_args_destroy            = GetObject<grpcsharp_channel_args_destroy_delegate>(new IntPtr(p + 0x168), ReversePrism.DataModels.grpcsharp_channel_args_destroy_delegate.FromPointer); // 0x168 Grpcsharp_channel_args_destroy ( ModelClassType grpcsharp_channel_args_destroy_delegate grpcsharp_channel_args_destroy_delegate grpcsharp_channel_args_destroy_delegate Pointer )
            value.Grpcsharp_override_default_ssl_roots      = GetObject<grpcsharp_override_default_ssl_roots_delegate>(new IntPtr(p + 0x170), ReversePrism.DataModels.grpcsharp_override_default_ssl_roots_delegate.FromPointer); // 0x170 Grpcsharp_override_default_ssl_roots ( ModelClassType grpcsharp_override_default_ssl_roots_delegate grpcsharp_override_default_ssl_roots_delegate grpcsharp_override_default_ssl_roots_delegate Pointer )
            value.Grpcsharp_ssl_credentials_create          = GetObject<grpcsharp_ssl_credentials_create_delegate>(new IntPtr(p + 0x178), ReversePrism.DataModels.grpcsharp_ssl_credentials_create_delegate.FromPointer); // 0x178 Grpcsharp_ssl_credentials_create ( ModelClassType grpcsharp_ssl_credentials_create_delegate grpcsharp_ssl_credentials_create_delegate grpcsharp_ssl_credentials_create_delegate Pointer )
            value.Grpcsharp_composite_channel_credentials_create = GetObject<grpcsharp_composite_channel_credentials_create_delegate>(new IntPtr(p + 0x180), ReversePrism.DataModels.grpcsharp_composite_channel_credentials_create_delegate.FromPointer); // 0x180 Grpcsharp_composite_channel_credentials_create ( ModelClassType grpcsharp_composite_channel_credentials_create_delegate grpcsharp_composite_channel_credentials_create_delegate grpcsharp_composite_channel_credentials_create_delegate Pointer )
            value.Grpcsharp_channel_credentials_release     = GetObject<grpcsharp_channel_credentials_release_delegate>(new IntPtr(p + 0x188), ReversePrism.DataModels.grpcsharp_channel_credentials_release_delegate.FromPointer); // 0x188 Grpcsharp_channel_credentials_release ( ModelClassType grpcsharp_channel_credentials_release_delegate grpcsharp_channel_credentials_release_delegate grpcsharp_channel_credentials_release_delegate Pointer )
            value.Grpcsharp_insecure_channel_create         = GetObject<grpcsharp_insecure_channel_create_delegate>(new IntPtr(p + 0x190), ReversePrism.DataModels.grpcsharp_insecure_channel_create_delegate.FromPointer); // 0x190 Grpcsharp_insecure_channel_create ( ModelClassType grpcsharp_insecure_channel_create_delegate grpcsharp_insecure_channel_create_delegate grpcsharp_insecure_channel_create_delegate Pointer )
            value.Grpcsharp_secure_channel_create           = GetObject<grpcsharp_secure_channel_create_delegate>(new IntPtr(p + 0x198), ReversePrism.DataModels.grpcsharp_secure_channel_create_delegate.FromPointer); // 0x198 Grpcsharp_secure_channel_create ( ModelClassType grpcsharp_secure_channel_create_delegate grpcsharp_secure_channel_create_delegate grpcsharp_secure_channel_create_delegate Pointer )
            value.Grpcsharp_channel_create_call             = GetObject<grpcsharp_channel_create_call_delegate>(new IntPtr(p + 0x1A0), ReversePrism.DataModels.grpcsharp_channel_create_call_delegate.FromPointer); // 0x1A0 Grpcsharp_channel_create_call ( ModelClassType grpcsharp_channel_create_call_delegate grpcsharp_channel_create_call_delegate grpcsharp_channel_create_call_delegate Pointer )
            value.Grpcsharp_channel_check_connectivity_state = GetObject<grpcsharp_channel_check_connectivity_state_delegate>(new IntPtr(p + 0x1A8), ReversePrism.DataModels.grpcsharp_channel_check_connectivity_state_delegate.FromPointer); // 0x1A8 Grpcsharp_channel_check_connectivity_state ( ModelClassType grpcsharp_channel_check_connectivity_state_delegate grpcsharp_channel_check_connectivity_state_delegate grpcsharp_channel_check_connectivity_state_delegate Pointer )
            value.Grpcsharp_channel_watch_connectivity_state = GetObject<grpcsharp_channel_watch_connectivity_state_delegate>(new IntPtr(p + 0x1B0), ReversePrism.DataModels.grpcsharp_channel_watch_connectivity_state_delegate.FromPointer); // 0x1B0 Grpcsharp_channel_watch_connectivity_state ( ModelClassType grpcsharp_channel_watch_connectivity_state_delegate grpcsharp_channel_watch_connectivity_state_delegate grpcsharp_channel_watch_connectivity_state_delegate Pointer )
            value.Grpcsharp_channel_get_target              = GetObject<grpcsharp_channel_get_target_delegate>(new IntPtr(p + 0x1B8), ReversePrism.DataModels.grpcsharp_channel_get_target_delegate.FromPointer); // 0x1B8 Grpcsharp_channel_get_target ( ModelClassType grpcsharp_channel_get_target_delegate grpcsharp_channel_get_target_delegate grpcsharp_channel_get_target_delegate Pointer )
            value.Grpcsharp_channel_destroy                 = GetObject<grpcsharp_channel_destroy_delegate>(new IntPtr(p + 0x1C0), ReversePrism.DataModels.grpcsharp_channel_destroy_delegate.FromPointer); // 0x1C0 Grpcsharp_channel_destroy   ( ModelClassType grpcsharp_channel_destroy_delegate grpcsharp_channel_destroy_delegate grpcsharp_channel_destroy_delegate Pointer )
            value.Grpcsharp_sizeof_grpc_event               = GetObject<grpcsharp_sizeof_grpc_event_delegate>(new IntPtr(p + 0x1C8), ReversePrism.DataModels.grpcsharp_sizeof_grpc_event_delegate.FromPointer); // 0x1C8 Grpcsharp_sizeof_grpc_event ( ModelClassType grpcsharp_sizeof_grpc_event_delegate grpcsharp_sizeof_grpc_event_delegate grpcsharp_sizeof_grpc_event_delegate Pointer )
            value.Grpcsharp_completion_queue_create_async   = GetObject<grpcsharp_completion_queue_create_async_delegate>(new IntPtr(p + 0x1D0), ReversePrism.DataModels.grpcsharp_completion_queue_create_async_delegate.FromPointer); // 0x1D0 Grpcsharp_completion_queue_create_async ( ModelClassType grpcsharp_completion_queue_create_async_delegate grpcsharp_completion_queue_create_async_delegate grpcsharp_completion_queue_create_async_delegate Pointer )
            value.Grpcsharp_completion_queue_create_sync    = GetObject<grpcsharp_completion_queue_create_sync_delegate>(new IntPtr(p + 0x1D8), ReversePrism.DataModels.grpcsharp_completion_queue_create_sync_delegate.FromPointer); // 0x1D8 Grpcsharp_completion_queue_create_sync ( ModelClassType grpcsharp_completion_queue_create_sync_delegate grpcsharp_completion_queue_create_sync_delegate grpcsharp_completion_queue_create_sync_delegate Pointer )
            value.Grpcsharp_completion_queue_shutdown       = GetObject<grpcsharp_completion_queue_shutdown_delegate>(new IntPtr(p + 0x1E0), ReversePrism.DataModels.grpcsharp_completion_queue_shutdown_delegate.FromPointer); // 0x1E0 Grpcsharp_completion_queue_shutdown ( ModelClassType grpcsharp_completion_queue_shutdown_delegate grpcsharp_completion_queue_shutdown_delegate grpcsharp_completion_queue_shutdown_delegate Pointer )
            value.Grpcsharp_completion_queue_next           = GetObject<grpcsharp_completion_queue_next_delegate>(new IntPtr(p + 0x1E8), ReversePrism.DataModels.grpcsharp_completion_queue_next_delegate.FromPointer); // 0x1E8 Grpcsharp_completion_queue_next ( ModelClassType grpcsharp_completion_queue_next_delegate grpcsharp_completion_queue_next_delegate grpcsharp_completion_queue_next_delegate Pointer )
            value.Grpcsharp_completion_queue_pluck          = GetObject<grpcsharp_completion_queue_pluck_delegate>(new IntPtr(p + 0x1F0), ReversePrism.DataModels.grpcsharp_completion_queue_pluck_delegate.FromPointer); // 0x1F0 Grpcsharp_completion_queue_pluck ( ModelClassType grpcsharp_completion_queue_pluck_delegate grpcsharp_completion_queue_pluck_delegate grpcsharp_completion_queue_pluck_delegate Pointer )
            value.Grpcsharp_completion_queue_destroy        = GetObject<grpcsharp_completion_queue_destroy_delegate>(new IntPtr(p + 0x1F8), ReversePrism.DataModels.grpcsharp_completion_queue_destroy_delegate.FromPointer); // 0x1F8 Grpcsharp_completion_queue_destroy ( ModelClassType grpcsharp_completion_queue_destroy_delegate grpcsharp_completion_queue_destroy_delegate grpcsharp_completion_queue_destroy_delegate Pointer )
            value.Gprsharp_free                             = GetObject<gprsharp_free_delegate>(new IntPtr(p + 0x200), ReversePrism.DataModels.gprsharp_free_delegate.FromPointer); // 0x200 Gprsharp_free               ( ModelClassType gprsharp_free_delegate gprsharp_free_delegate gprsharp_free_delegate Pointer )
            value.Grpcsharp_metadata_array_create           = GetObject<grpcsharp_metadata_array_create_delegate>(new IntPtr(p + 0x208), ReversePrism.DataModels.grpcsharp_metadata_array_create_delegate.FromPointer); // 0x208 Grpcsharp_metadata_array_create ( ModelClassType grpcsharp_metadata_array_create_delegate grpcsharp_metadata_array_create_delegate grpcsharp_metadata_array_create_delegate Pointer )
            value.Grpcsharp_metadata_array_add              = GetObject<grpcsharp_metadata_array_add_delegate>(new IntPtr(p + 0x210), ReversePrism.DataModels.grpcsharp_metadata_array_add_delegate.FromPointer); // 0x210 Grpcsharp_metadata_array_add ( ModelClassType grpcsharp_metadata_array_add_delegate grpcsharp_metadata_array_add_delegate grpcsharp_metadata_array_add_delegate Pointer )
            value.Grpcsharp_metadata_array_count            = GetObject<grpcsharp_metadata_array_count_delegate>(new IntPtr(p + 0x218), ReversePrism.DataModels.grpcsharp_metadata_array_count_delegate.FromPointer); // 0x218 Grpcsharp_metadata_array_count ( ModelClassType grpcsharp_metadata_array_count_delegate grpcsharp_metadata_array_count_delegate grpcsharp_metadata_array_count_delegate Pointer )
            value.Grpcsharp_metadata_array_get_key          = GetObject<grpcsharp_metadata_array_get_key_delegate>(new IntPtr(p + 0x220), ReversePrism.DataModels.grpcsharp_metadata_array_get_key_delegate.FromPointer); // 0x220 Grpcsharp_metadata_array_get_key ( ModelClassType grpcsharp_metadata_array_get_key_delegate grpcsharp_metadata_array_get_key_delegate grpcsharp_metadata_array_get_key_delegate Pointer )
            value.Grpcsharp_metadata_array_get_value        = GetObject<grpcsharp_metadata_array_get_value_delegate>(new IntPtr(p + 0x228), ReversePrism.DataModels.grpcsharp_metadata_array_get_value_delegate.FromPointer); // 0x228 Grpcsharp_metadata_array_get_value ( ModelClassType grpcsharp_metadata_array_get_value_delegate grpcsharp_metadata_array_get_value_delegate grpcsharp_metadata_array_get_value_delegate Pointer )
            value.Grpcsharp_metadata_array_destroy_full     = GetObject<grpcsharp_metadata_array_destroy_full_delegate>(new IntPtr(p + 0x230), ReversePrism.DataModels.grpcsharp_metadata_array_destroy_full_delegate.FromPointer); // 0x230 Grpcsharp_metadata_array_destroy_full ( ModelClassType grpcsharp_metadata_array_destroy_full_delegate grpcsharp_metadata_array_destroy_full_delegate grpcsharp_metadata_array_destroy_full_delegate Pointer )
            value.Grpcsharp_redirect_log                    = GetObject<grpcsharp_redirect_log_delegate>(new IntPtr(p + 0x238), ReversePrism.DataModels.grpcsharp_redirect_log_delegate.FromPointer); // 0x238 Grpcsharp_redirect_log      ( ModelClassType grpcsharp_redirect_log_delegate grpcsharp_redirect_log_delegate grpcsharp_redirect_log_delegate Pointer )
            value.Grpcsharp_native_callback_dispatcher_init = GetObject<grpcsharp_native_callback_dispatcher_init_delegate>(new IntPtr(p + 0x240), ReversePrism.DataModels.grpcsharp_native_callback_dispatcher_init_delegate.FromPointer); // 0x240 Grpcsharp_native_callback_dispatcher_init ( ModelClassType grpcsharp_native_callback_dispatcher_init_delegate grpcsharp_native_callback_dispatcher_init_delegate grpcsharp_native_callback_dispatcher_init_delegate Pointer )
            value.Grpcsharp_metadata_credentials_create_from_plugin = GetObject<grpcsharp_metadata_credentials_create_from_plugin_delegate>(new IntPtr(p + 0x248), ReversePrism.DataModels.grpcsharp_metadata_credentials_create_from_plugin_delegate.FromPointer); // 0x248 Grpcsharp_metadata_credentials_create_from_plugin ( ModelClassType grpcsharp_metadata_credentials_create_from_plugin_delegate grpcsharp_metadata_credentials_create_from_plugin_delegate grpcsharp_metadata_credentials_create_from_plugin_delegate Pointer )
            value.Grpcsharp_metadata_credentials_notify_from_plugin = GetObject<grpcsharp_metadata_credentials_notify_from_plugin_delegate>(new IntPtr(p + 0x250), ReversePrism.DataModels.grpcsharp_metadata_credentials_notify_from_plugin_delegate.FromPointer); // 0x250 Grpcsharp_metadata_credentials_notify_from_plugin ( ModelClassType grpcsharp_metadata_credentials_notify_from_plugin_delegate grpcsharp_metadata_credentials_notify_from_plugin_delegate grpcsharp_metadata_credentials_notify_from_plugin_delegate Pointer )
            value.Grpcsharp_ssl_server_credentials_create   = GetObject<grpcsharp_ssl_server_credentials_create_delegate>(new IntPtr(p + 0x258), ReversePrism.DataModels.grpcsharp_ssl_server_credentials_create_delegate.FromPointer); // 0x258 Grpcsharp_ssl_server_credentials_create ( ModelClassType grpcsharp_ssl_server_credentials_create_delegate grpcsharp_ssl_server_credentials_create_delegate grpcsharp_ssl_server_credentials_create_delegate Pointer )
            value.Grpcsharp_server_credentials_release      = GetObject<grpcsharp_server_credentials_release_delegate>(new IntPtr(p + 0x260), ReversePrism.DataModels.grpcsharp_server_credentials_release_delegate.FromPointer); // 0x260 Grpcsharp_server_credentials_release ( ModelClassType grpcsharp_server_credentials_release_delegate grpcsharp_server_credentials_release_delegate grpcsharp_server_credentials_release_delegate Pointer )
            value.Grpcsharp_server_create                   = GetObject<grpcsharp_server_create_delegate>(new IntPtr(p + 0x268), ReversePrism.DataModels.grpcsharp_server_create_delegate.FromPointer); // 0x268 Grpcsharp_server_create     ( ModelClassType grpcsharp_server_create_delegate grpcsharp_server_create_delegate grpcsharp_server_create_delegate Pointer )
            value.Grpcsharp_server_register_completion_queue = GetObject<grpcsharp_server_register_completion_queue_delegate>(new IntPtr(p + 0x270), ReversePrism.DataModels.grpcsharp_server_register_completion_queue_delegate.FromPointer); // 0x270 Grpcsharp_server_register_completion_queue ( ModelClassType grpcsharp_server_register_completion_queue_delegate grpcsharp_server_register_completion_queue_delegate grpcsharp_server_register_completion_queue_delegate Pointer )
            value.Grpcsharp_server_add_insecure_http2_port  = GetObject<grpcsharp_server_add_insecure_http2_port_delegate>(new IntPtr(p + 0x278), ReversePrism.DataModels.grpcsharp_server_add_insecure_http2_port_delegate.FromPointer); // 0x278 Grpcsharp_server_add_insecure_http2_port ( ModelClassType grpcsharp_server_add_insecure_http2_port_delegate grpcsharp_server_add_insecure_http2_port_delegate grpcsharp_server_add_insecure_http2_port_delegate Pointer )
            value.Grpcsharp_server_add_secure_http2_port    = GetObject<grpcsharp_server_add_secure_http2_port_delegate>(new IntPtr(p + 0x280), ReversePrism.DataModels.grpcsharp_server_add_secure_http2_port_delegate.FromPointer); // 0x280 Grpcsharp_server_add_secure_http2_port ( ModelClassType grpcsharp_server_add_secure_http2_port_delegate grpcsharp_server_add_secure_http2_port_delegate grpcsharp_server_add_secure_http2_port_delegate Pointer )
            value.Grpcsharp_server_start                    = GetObject<grpcsharp_server_start_delegate>(new IntPtr(p + 0x288), ReversePrism.DataModels.grpcsharp_server_start_delegate.FromPointer); // 0x288 Grpcsharp_server_start      ( ModelClassType grpcsharp_server_start_delegate grpcsharp_server_start_delegate grpcsharp_server_start_delegate Pointer )
            value.Grpcsharp_server_request_call             = GetObject<grpcsharp_server_request_call_delegate>(new IntPtr(p + 0x290), ReversePrism.DataModels.grpcsharp_server_request_call_delegate.FromPointer); // 0x290 Grpcsharp_server_request_call ( ModelClassType grpcsharp_server_request_call_delegate grpcsharp_server_request_call_delegate grpcsharp_server_request_call_delegate Pointer )
            value.Grpcsharp_server_cancel_all_calls         = GetObject<grpcsharp_server_cancel_all_calls_delegate>(new IntPtr(p + 0x298), ReversePrism.DataModels.grpcsharp_server_cancel_all_calls_delegate.FromPointer); // 0x298 Grpcsharp_server_cancel_all_calls ( ModelClassType grpcsharp_server_cancel_all_calls_delegate grpcsharp_server_cancel_all_calls_delegate grpcsharp_server_cancel_all_calls_delegate Pointer )
            value.Grpcsharp_server_shutdown_and_notify_callback = GetObject<grpcsharp_server_shutdown_and_notify_callback_delegate>(new IntPtr(p + 0x2A0), ReversePrism.DataModels.grpcsharp_server_shutdown_and_notify_callback_delegate.FromPointer); // 0x2A0 Grpcsharp_server_shutdown_and_notify_callback ( ModelClassType grpcsharp_server_shutdown_and_notify_callback_delegate grpcsharp_server_shutdown_and_notify_callback_delegate grpcsharp_server_shutdown_and_notify_callback_delegate Pointer )
            value.Grpcsharp_server_destroy                  = GetObject<grpcsharp_server_destroy_delegate>(new IntPtr(p + 0x2A8), ReversePrism.DataModels.grpcsharp_server_destroy_delegate.FromPointer); // 0x2A8 Grpcsharp_server_destroy    ( ModelClassType grpcsharp_server_destroy_delegate grpcsharp_server_destroy_delegate grpcsharp_server_destroy_delegate Pointer )
            value.Grpcsharp_call_auth_context               = GetObject<grpcsharp_call_auth_context_delegate>(new IntPtr(p + 0x2B0), ReversePrism.DataModels.grpcsharp_call_auth_context_delegate.FromPointer); // 0x2B0 Grpcsharp_call_auth_context ( ModelClassType grpcsharp_call_auth_context_delegate grpcsharp_call_auth_context_delegate grpcsharp_call_auth_context_delegate Pointer )
            value.Grpcsharp_auth_context_peer_identity_property_name = GetObject<grpcsharp_auth_context_peer_identity_property_name_delegate>(new IntPtr(p + 0x2B8), ReversePrism.DataModels.grpcsharp_auth_context_peer_identity_property_name_delegate.FromPointer); // 0x2B8 Grpcsharp_auth_context_peer_identity_property_name ( ModelClassType grpcsharp_auth_context_peer_identity_property_name_delegate grpcsharp_auth_context_peer_identity_property_name_delegate grpcsharp_auth_context_peer_identity_property_name_delegate Pointer )
            value.Grpcsharp_auth_context_property_iterator  = GetObject<grpcsharp_auth_context_property_iterator_delegate>(new IntPtr(p + 0x2C0), ReversePrism.DataModels.grpcsharp_auth_context_property_iterator_delegate.FromPointer); // 0x2C0 Grpcsharp_auth_context_property_iterator ( ModelClassType grpcsharp_auth_context_property_iterator_delegate grpcsharp_auth_context_property_iterator_delegate grpcsharp_auth_context_property_iterator_delegate Pointer )
            value.Grpcsharp_auth_property_iterator_next     = GetObject<grpcsharp_auth_property_iterator_next_delegate>(new IntPtr(p + 0x2C8), ReversePrism.DataModels.grpcsharp_auth_property_iterator_next_delegate.FromPointer); // 0x2C8 Grpcsharp_auth_property_iterator_next ( ModelClassType grpcsharp_auth_property_iterator_next_delegate grpcsharp_auth_property_iterator_next_delegate grpcsharp_auth_property_iterator_next_delegate Pointer )
            value.Grpcsharp_auth_context_release            = GetObject<grpcsharp_auth_context_release_delegate>(new IntPtr(p + 0x2D0), ReversePrism.DataModels.grpcsharp_auth_context_release_delegate.FromPointer); // 0x2D0 Grpcsharp_auth_context_release ( ModelClassType grpcsharp_auth_context_release_delegate grpcsharp_auth_context_release_delegate grpcsharp_auth_context_release_delegate Pointer )
            value.Grpcsharp_slice_buffer_create             = GetObject<grpcsharp_slice_buffer_create_delegate>(new IntPtr(p + 0x2D8), ReversePrism.DataModels.grpcsharp_slice_buffer_create_delegate.FromPointer); // 0x2D8 Grpcsharp_slice_buffer_create ( ModelClassType grpcsharp_slice_buffer_create_delegate grpcsharp_slice_buffer_create_delegate grpcsharp_slice_buffer_create_delegate Pointer )
            value.Grpcsharp_slice_buffer_adjust_tail_space  = GetObject<grpcsharp_slice_buffer_adjust_tail_space_delegate>(new IntPtr(p + 0x2E0), ReversePrism.DataModels.grpcsharp_slice_buffer_adjust_tail_space_delegate.FromPointer); // 0x2E0 Grpcsharp_slice_buffer_adjust_tail_space ( ModelClassType grpcsharp_slice_buffer_adjust_tail_space_delegate grpcsharp_slice_buffer_adjust_tail_space_delegate grpcsharp_slice_buffer_adjust_tail_space_delegate Pointer )
            value.Grpcsharp_slice_buffer_slice_count        = GetObject<grpcsharp_slice_buffer_slice_count_delegate>(new IntPtr(p + 0x2E8), ReversePrism.DataModels.grpcsharp_slice_buffer_slice_count_delegate.FromPointer); // 0x2E8 Grpcsharp_slice_buffer_slice_count ( ModelClassType grpcsharp_slice_buffer_slice_count_delegate grpcsharp_slice_buffer_slice_count_delegate grpcsharp_slice_buffer_slice_count_delegate Pointer )
            value.Grpcsharp_slice_buffer_slice_peek         = GetObject<grpcsharp_slice_buffer_slice_peek_delegate>(new IntPtr(p + 0x2F0), ReversePrism.DataModels.grpcsharp_slice_buffer_slice_peek_delegate.FromPointer); // 0x2F0 Grpcsharp_slice_buffer_slice_peek ( ModelClassType grpcsharp_slice_buffer_slice_peek_delegate grpcsharp_slice_buffer_slice_peek_delegate grpcsharp_slice_buffer_slice_peek_delegate Pointer )
            value.Grpcsharp_slice_buffer_reset_and_unref    = GetObject<grpcsharp_slice_buffer_reset_and_unref_delegate>(new IntPtr(p + 0x2F8), ReversePrism.DataModels.grpcsharp_slice_buffer_reset_and_unref_delegate.FromPointer); // 0x2F8 Grpcsharp_slice_buffer_reset_and_unref ( ModelClassType grpcsharp_slice_buffer_reset_and_unref_delegate grpcsharp_slice_buffer_reset_and_unref_delegate grpcsharp_slice_buffer_reset_and_unref_delegate Pointer )
            value.Grpcsharp_slice_buffer_destroy            = GetObject<grpcsharp_slice_buffer_destroy_delegate>(new IntPtr(p + 0x300), ReversePrism.DataModels.grpcsharp_slice_buffer_destroy_delegate.FromPointer); // 0x300 Grpcsharp_slice_buffer_destroy ( ModelClassType grpcsharp_slice_buffer_destroy_delegate grpcsharp_slice_buffer_destroy_delegate grpcsharp_slice_buffer_destroy_delegate Pointer )
            value.Gprsharp_now                              = GetObject<gprsharp_now_delegate>(new IntPtr(p + 0x308), ReversePrism.DataModels.gprsharp_now_delegate.FromPointer); // 0x308 Gprsharp_now                ( ModelClassType gprsharp_now_delegate gprsharp_now_delegate gprsharp_now_delegate Pointer )
            value.Gprsharp_inf_future                       = GetObject<gprsharp_inf_future_delegate>(new IntPtr(p + 0x310), ReversePrism.DataModels.gprsharp_inf_future_delegate.FromPointer); // 0x310 Gprsharp_inf_future         ( ModelClassType gprsharp_inf_future_delegate gprsharp_inf_future_delegate gprsharp_inf_future_delegate Pointer )
            value.Gprsharp_inf_past                         = GetObject<gprsharp_inf_past_delegate>(new IntPtr(p + 0x318), ReversePrism.DataModels.gprsharp_inf_past_delegate.FromPointer); // 0x318 Gprsharp_inf_past           ( ModelClassType gprsharp_inf_past_delegate gprsharp_inf_past_delegate gprsharp_inf_past_delegate Pointer )
            value.Gprsharp_convert_clock_type               = GetObject<gprsharp_convert_clock_type_delegate>(new IntPtr(p + 0x320), ReversePrism.DataModels.gprsharp_convert_clock_type_delegate.FromPointer); // 0x320 Gprsharp_convert_clock_type ( ModelClassType gprsharp_convert_clock_type_delegate gprsharp_convert_clock_type_delegate gprsharp_convert_clock_type_delegate Pointer )
            value.Gprsharp_sizeof_timespec                  = GetObject<gprsharp_sizeof_timespec_delegate>(new IntPtr(p + 0x328), ReversePrism.DataModels.gprsharp_sizeof_timespec_delegate.FromPointer); // 0x328 Gprsharp_sizeof_timespec    ( ModelClassType gprsharp_sizeof_timespec_delegate gprsharp_sizeof_timespec_delegate gprsharp_sizeof_timespec_delegate Pointer )
            value.Grpcsharp_test_callback                   = GetObject<grpcsharp_test_callback_delegate>(new IntPtr(p + 0x330), ReversePrism.DataModels.grpcsharp_test_callback_delegate.FromPointer); // 0x330 Grpcsharp_test_callback     ( ModelClassType grpcsharp_test_callback_delegate grpcsharp_test_callback_delegate grpcsharp_test_callback_delegate Pointer )
            value.Grpcsharp_test_nop                        = GetObject<grpcsharp_test_nop_delegate>(new IntPtr(p + 0x338), ReversePrism.DataModels.grpcsharp_test_nop_delegate.FromPointer); // 0x338 Grpcsharp_test_nop          ( ModelClassType grpcsharp_test_nop_delegate grpcsharp_test_nop_delegate grpcsharp_test_nop_delegate Pointer )
            value.Grpcsharp_test_override_method            = GetObject<grpcsharp_test_override_method_delegate>(new IntPtr(p + 0x340), ReversePrism.DataModels.grpcsharp_test_override_method_delegate.FromPointer); // 0x340 Grpcsharp_test_override_method ( ModelClassType grpcsharp_test_override_method_delegate grpcsharp_test_override_method_delegate grpcsharp_test_override_method_delegate Pointer )
            value.Grpcsharp_test_call_start_unary_echo      = GetObject<grpcsharp_test_call_start_unary_echo_delegate>(new IntPtr(p + 0x348), ReversePrism.DataModels.grpcsharp_test_call_start_unary_echo_delegate.FromPointer); // 0x348 Grpcsharp_test_call_start_unary_echo ( ModelClassType grpcsharp_test_call_start_unary_echo_delegate grpcsharp_test_call_start_unary_echo_delegate grpcsharp_test_call_start_unary_echo_delegate Pointer )

            return value;
        }
    }
}
