using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    public enum CorElementType
    {
        End,
        Void,
        Boolean,
        Char,
        I1,
        U1,
        I2,
        U2,
        I4,
        U4,
        I8,
        U8,
        R4,
        R8,
        String,
        Ptr,
        ByRef,
        ValueType,
        Class,
        Var,
        Array,
        GenericInst,
        TypedByRef,
        I,
        U,
        FnPtr,
        Object,
        SzArray,
        MVar,
        CModReqd,
        CModOpt,
        Internal,
        Max,
        Modifier,
        Sentinel,
        Pinned,
        ELEMENT_TYPE_END,
        ELEMENT_TYPE_VOID,
        ELEMENT_TYPE_BOOLEAN,
        ELEMENT_TYPE_CHAR,
        ELEMENT_TYPE_I1,
        ELEMENT_TYPE_U1,
        ELEMENT_TYPE_I2,
        ELEMENT_TYPE_U2,
        ELEMENT_TYPE_I4,
        ELEMENT_TYPE_U4,
        ELEMENT_TYPE_I8,
        ELEMENT_TYPE_U8,
        ELEMENT_TYPE_R4,
        ELEMENT_TYPE_R8,
        ELEMENT_TYPE_STRING,
        ELEMENT_TYPE_PTR,
        ELEMENT_TYPE_BYREF,
        ELEMENT_TYPE_VALUETYPE,
        ELEMENT_TYPE_CLASS,
        ELEMENT_TYPE_VAR,
        ELEMENT_TYPE_ARRAY,
        ELEMENT_TYPE_GENERICINST,
        ELEMENT_TYPE_TYPEDBYREF,
        ELEMENT_TYPE_I,
        ELEMENT_TYPE_U,
        ELEMENT_TYPE_FNPTR,
        ELEMENT_TYPE_OBJECT,
        ELEMENT_TYPE_SZARRAY,
        ELEMENT_TYPE_MVAR,
        ELEMENT_TYPE_CMOD_REQD,
        ELEMENT_TYPE_CMOD_OPT,
        ELEMENT_TYPE_INTERNAL,
        ELEMENT_TYPE_MAX,
        ELEMENT_TYPE_MODIFIER,
        ELEMENT_TYPE_SENTINEL,
        ELEMENT_TYPE_PINNED,
    }
}
