using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    public enum BinXmlToken
    {
        Error,
        NotImpl,
        EOF,
        XmlDecl,
        Encoding,
        DocType,
        System,
        Public,
        Subset,
        Element,
        EndElem,
        Attr,
        EndAttrs,
        PI,
        Comment,
        CData,
        EndCData,
        Name,
        QName,
        XmlText,
        Nest,
        EndNest,
        Extn,
        NmFlush,
        SQL_BIT,
        SQL_TINYINT,
        SQL_SMALLINT,
        SQL_INT,
        SQL_BIGINT,
        SQL_REAL,
        SQL_FLOAT,
        SQL_MONEY,
        SQL_SMALLMONEY,
        SQL_DATETIME,
        SQL_SMALLDATETIME,
        SQL_DECIMAL,
        SQL_NUMERIC,
        SQL_UUID,
        SQL_VARBINARY,
        SQL_BINARY,
        SQL_IMAGE,
        SQL_CHAR,
        SQL_VARCHAR,
        SQL_TEXT,
        SQL_NVARCHAR,
        SQL_NCHAR,
        SQL_NTEXT,
        SQL_UDT,
        XSD_KATMAI_DATE,
        XSD_KATMAI_DATETIME,
        XSD_KATMAI_TIME,
        XSD_KATMAI_DATEOFFSET,
        XSD_KATMAI_DATETIMEOFFSET,
        XSD_KATMAI_TIMEOFFSET,
        XSD_BOOLEAN,
        XSD_TIME,
        XSD_DATETIME,
        XSD_DATE,
        XSD_BINHEX,
        XSD_BASE64,
        XSD_DECIMAL,
        XSD_BYTE,
        XSD_UNSIGNEDSHORT,
        XSD_UNSIGNEDINT,
        XSD_UNSIGNEDLONG,
        XSD_QNAME,
    }
}
