using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    public enum GenericDesktop
    {
        Undefined,
        Pointer,
        Mouse,
        Joystick,
        Gamepad,
        Keyboard,
        Keypad,
        MultiAxisController,
        TabletPCControls,
        AssistiveControl,
        X,
        Y,
        Z,
        Rx,
        Ry,
        Rz,
        Slider,
        Dial,
        Wheel,
        HatSwitch,
        CountedBuffer,
        ByteCount,
        MotionWakeup,
        Start,
        Select,
        Vx,
        Vy,
        Vz,
        Vbrx,
        Vbry,
        Vbrz,
        Vno,
        FeatureNotification,
        ResolutionMultiplier,
        SystemControl,
        SystemPowerDown,
        SystemSleep,
        SystemWakeUp,
        SystemContextMenu,
        SystemMainMenu,
        SystemAppMenu,
        SystemMenuHelp,
        SystemMenuExit,
        SystemMenuSelect,
        SystemMenuRight,
        SystemMenuLeft,
        SystemMenuUp,
        SystemMenuDown,
        SystemColdRestart,
        SystemWarmRestart,
        DpadUp,
        DpadDown,
        DpadRight,
        DpadLeft,
        SystemDock,
        SystemUndock,
        SystemSetup,
        SystemBreak,
        SystemDebuggerBreak,
        ApplicationBreak,
        ApplicationDebuggerBreak,
        SystemSpeakerMute,
        SystemHibernate,
        SystemDisplayInvert,
        SystemDisplayInternal,
        SystemDisplayExternal,
        SystemDisplayBoth,
        SystemDisplayDual,
        SystemDisplayToggleIntExt,
        SystemDisplaySwapPrimarySecondary,
        SystemDisplayLCDAutoScale,
    }
}
