using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    public enum SupportSkillType
    {
        LessonPPBonus,
        SPLessonPPBonus,
        AuditionPPBonus,
        MentalGuardBonus,
        MentalVoApeealRate,
        MentalDaApeealRate,
        MentalViApeealRate,
        AvoidVoAppealRate,
        AvoidDaAppealRate,
        AvoidViAppealRate,
        GuardFirstMentalBreakOnce,
        LimitPPBonus,
        AppealRateBonus,
        VoAppealRateBonus,
        DaAppealRateBonus,
        ViAppealRateBonus,
        VoUpDaViDown,
        DaUpVoViDown,
        ViUpVoDaDown,
        AvoidAppealRate,
        IdolSkillVoApeealUp,
        IdolSkillDaApeealUp,
        IdolSkillViApeealUp,
        MentalRecoverUp,
        PPRecoverUp,
        MinusMentalBreakTime,
        MentalRecoverUpWhenRecoverMentalBreak,
        ApeealRateOnceWhenRecoverMentalBreak,
        GetPPWhenRecoverMentalBreak,
        StartDashAppealRate,
        StartDashAppealVoRate,
        StartDashAppealDaRate,
        StartDashAppealViRate,
        GetAvoidRate,
        AppealRateWhenRecoverMental,
        AppealRateVoWhenRecoverMental,
        AppealRateDaWhenRecoverMental,
        AppealRateViWhenRecoverMental,
        AppeelBonusOnceWhenSearch,
        VoAppeelBonusOnceWhenSearch,
        DaAppeelBonusOnceWhenSearch,
        ViAppeelBonusOnceWhenSearch,
        AppeelBonusOnceWhenMaxHandIncrease,
        VoAppeelBonusOnceWhenMaxHandIncrease,
        DaAppeelBonusOnceWhenMaxHandIncrease,
        ViAppeelBonusOnceWhenMaxHandIncrease,
        PPSpeedUpWhenMePercent,
        AppealBonusWhenMaxHandNum,
        MentalGuardRate,
        AppealBonusWhenOpponentMentalBreak,
        AppealBonusWhenCostDown,
        MentalDamageUpFromOpponent,
        AddMaxHandNumWhenRecoverMentalBreak,
        StartDashMaxHandCount,
        StartDashRandomCostDown,
        RemoveCardWhenAfterTime,
        ForcePinchWhenAfterTime,
        LastRunPinch,
        RecoverMentalWhenUseCostDownCard,
        GetPPWhenRemoveCard,
        DrawWhenRemoveCard,
        RecoverMentalWhenSearch,
        MentalGuardWhenSearch,
        GetPPWhenMaxHandIncrease,
        MaxHandNumUntilDamageCount,
        MeDagameZeroUntilDamageCount,
        OpponentPPSpeedRate,
        OverHealToMentalGuard,
        StartDashCostDownMaxCostCard,
        RecoverMentalPer10Sec,
        GetAppealWhenUseCardCount,
        GetAppealBonusWhenUseCardCount,
        GetPPWhenMentalDamage,
        AppealBonusUntilCardUseCount,
        AppealBonusVoUntilCardUseCount,
        AppealBonusDaUntilCardUseCount,
        AppealBonusViUntilCardUseCount,
        IdolSkillCostDownUntilIdolSkillUseCount,
        GetPPWhenAvoid,
    }
}
