using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    // 010 ConstraintNames                          00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer
    // 018 Namespaces                               0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer
    // 020 Autogenerated                            0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer
    // 028 Prefixes                                 0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer
    // 030 Ds                                       000186680790 ModelClassType DataSet DataSet DataSet Pointer
    // 038 Tables                                   00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer
    // 040 Relations                                00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer
    // 048 Dc                                       000186595990 ModelClassType XmlDocument XmlDocument XmlDocument Pointer
    // 050 SRoot                                    000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer
    // 058 PrefixCount                              0001865F2AF0 ModelPrimitiveType int int int Int32
    // 05C SchFormat                                0001866E94D0 ModelEnumType SchemaFormat SchemaFormat SchemaFormat Int32
    // 060 FilePath                                 000186671910 ModelPrimitiveType string string string String
    // 068 FileName                                 000186671910 ModelPrimitiveType string string string String
    // 070 FileExt                                  000186671910 ModelPrimitiveType string string string String
    // 078 DsElement                                000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer
    // 080 ConstraintSeparator                      000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer
    // 088 _targetConverter                         Converter`2<Type, string> IL2CPP_TYPE_GENERICINST
    public partial class XmlTreeGen : DataModel
    {
        public ArrayList?                               ConstraintNames                         { get; set; }
        public Hashtable?                               Namespaces                              { get; set; }
        public Hashtable?                               Autogenerated                           { get; set; }
        public Hashtable?                               Prefixes                                { get; set; }
        public DataSet?                                 Ds                                      { get; set; }
        public ArrayList?                               Tables                                  { get; set; }
        public ArrayList?                               Relations                               { get; set; }
        public XmlDocument?                             Dc                                      { get; set; }
        public XmlElement?                              SRoot                                   { get; set; }
        public int                                      PrefixCount                             { get; set; }
        public SchemaFormat                             SchFormat                               { get; set; }
        public string                                   FilePath                                { get; set; }
        public string                                   FileName                                { get; set; }
        public string                                   FileExt                                 { get; set; }
        public XmlElement?                              DsElement                               { get; set; }
        public XmlElement?                              ConstraintSeparator                     { get; set; }

        public static XmlTreeGen? FromPointer(IntPtr p0)
        {
            if(p0 == IntPtr.Zero)
                return null;

            var p       = p0.ToInt64();
            var value   = new XmlTreeGen() { Pointer= p0 };

            value.ConstraintNames                           = GetObject<ArrayList>(new IntPtr(p + 0x010), ReversePrism.DataModels.ArrayList.FromPointer); // 0246689E4490 0x10 ConstraintNames             ( 00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Namespaces                                = GetObject<Hashtable>(new IntPtr(p + 0x018), ReversePrism.DataModels.Hashtable.FromPointer); // 0246689E44B0 0x18 Namespaces                  ( 0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Autogenerated                             = GetObject<Hashtable>(new IntPtr(p + 0x020), ReversePrism.DataModels.Hashtable.FromPointer); // 0246689E44D0 0x20 Autogenerated               ( 0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Prefixes                                  = GetObject<Hashtable>(new IntPtr(p + 0x028), ReversePrism.DataModels.Hashtable.FromPointer); // 0246689E44F0 0x28 Prefixes                    ( 0001865DE360 ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Ds                                        = GetObject<DataSet>(new IntPtr(p + 0x030), ReversePrism.DataModels.DataSet.FromPointer); // 0246689E4510 0x30 Ds                          ( 000186680790 ModelClassType DataSet DataSet DataSet Pointer )
            value.Tables                                    = GetObject<ArrayList>(new IntPtr(p + 0x038), ReversePrism.DataModels.ArrayList.FromPointer); // 0246689E4530 0x38 Tables                      ( 00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Relations                                 = GetObject<ArrayList>(new IntPtr(p + 0x040), ReversePrism.DataModels.ArrayList.FromPointer); // 0246689E4550 0x40 Relations                   ( 00018658A070 ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Dc                                        = GetObject<XmlDocument>(new IntPtr(p + 0x048), ReversePrism.DataModels.XmlDocument.FromPointer); // 0246689E4570 0x48 Dc                          ( 000186595990 ModelClassType XmlDocument XmlDocument XmlDocument Pointer )
            value.SRoot                                     = GetObject<XmlElement>(new IntPtr(p + 0x050), ReversePrism.DataModels.XmlElement.FromPointer); // 0246689E4590 0x50 SRoot                       ( 000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer )
            value.PrefixCount                               = GetInt32(new IntPtr(p + 0x058)); // 0246689E45B0 0x58 PrefixCount                 ( 0001865F2AF0 ModelPrimitiveType int int int Int32 )
            value.SchFormat                                 = (SchemaFormat)GetInt32(new IntPtr(p + 0x05C)); // 0246689E45D0 0x5C SchFormat                   ( 0001866E94D0 ModelEnumType SchemaFormat SchemaFormat SchemaFormat Int32 )
            value.FilePath                                  = GetString(new IntPtr(p + 0x060)); // 0246689E45F0 0x60 FilePath                    ( 000186671910 ModelPrimitiveType string string string String )
            value.FileName                                  = GetString(new IntPtr(p + 0x068)); // 0246689E4610 0x68 FileName                    ( 000186671910 ModelPrimitiveType string string string String )
            value.FileExt                                   = GetString(new IntPtr(p + 0x070)); // 0246689E4630 0x70 FileExt                     ( 000186671910 ModelPrimitiveType string string string String )
            value.DsElement                                 = GetObject<XmlElement>(new IntPtr(p + 0x078), ReversePrism.DataModels.XmlElement.FromPointer); // 0246689E4650 0x78 DsElement                   ( 000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer )
            value.ConstraintSeparator                       = GetObject<XmlElement>(new IntPtr(p + 0x080), ReversePrism.DataModels.XmlElement.FromPointer); // 0246689E4670 0x80 ConstraintSeparator         ( 000186597700 ModelClassType XmlElement XmlElement XmlElement Pointer )

            return value;
        }
    }
}
