using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism.DataModels
{
    using static ModelMarshaler;

    // 010 ConstraintNames                          ModelClassType ArrayList ArrayList ArrayList Pointer
    // 018 Namespaces                               ModelClassType Hashtable Hashtable Hashtable Pointer
    // 020 Autogenerated                            ModelClassType Hashtable Hashtable Hashtable Pointer
    // 028 Prefixes                                 ModelClassType Hashtable Hashtable Hashtable Pointer
    // 030 Ds                                       ModelClassType DataSet DataSet DataSet Pointer
    // 038 Tables                                   ModelClassType ArrayList ArrayList ArrayList Pointer
    // 040 Relations                                ModelClassType ArrayList ArrayList ArrayList Pointer
    // 048 Dc                                       ModelClassType XmlDocument XmlDocument XmlDocument Pointer
    // 050 SRoot                                    ModelClassType XmlElement XmlElement XmlElement Pointer
    // 058 PrefixCount                              ModelPrimitiveType int int int Int32
    // 05C SchFormat                                ModelEnumType SchemaFormat SchemaFormat SchemaFormat Int32
    // 060 FilePath                                 ModelPrimitiveType string string string String
    // 068 FileName                                 ModelPrimitiveType string string string String
    // 070 FileExt                                  ModelPrimitiveType string string string String
    // 078 DsElement                                ModelClassType XmlElement XmlElement XmlElement Pointer
    // 080 ConstraintSeparator                      ModelClassType XmlElement XmlElement XmlElement Pointer
    // 088 _targetConverter                         Converter`2<Type, string> IL2CPP_TYPE_GENERICINST
    public partial class XmlTreeGen : DataModel
    {
        public ArrayList?                               ConstraintNames                         { get; set; }
        public Hashtable?                               Namespaces                              { get; set; }
        public Hashtable?                               Autogenerated                           { get; set; }
        public Hashtable?                               Prefixes                                { get; set; }
        public DataSet?                                 Ds                                      { get; set; }
        public ArrayList?                               Tables                                  { get; set; }
        public ArrayList?                               Relations                               { get; set; }
        public XmlDocument?                             Dc                                      { get; set; }
        public XmlElement?                              SRoot                                   { get; set; }
        public int                                      PrefixCount                             { get; set; }
        public SchemaFormat                             SchFormat                               { get; set; }
        public string                                   FilePath                                { get; set; }
        public string                                   FileName                                { get; set; }
        public string                                   FileExt                                 { get; set; }
        public XmlElement?                              DsElement                               { get; set; }
        public XmlElement?                              ConstraintSeparator                     { get; set; }

        public static XmlTreeGen? FromPointer(IntPtr p0)
        {
            if(p0 == IntPtr.Zero)
                return null;

            var p       = p0.ToInt64();
            var value   = new XmlTreeGen() { Pointer= p0 };

            value.ConstraintNames                           = GetObject<ArrayList>(new IntPtr(p + 0x010), ReversePrism.DataModels.ArrayList.FromPointer); // 0x10 ConstraintNames             ( ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Namespaces                                = GetObject<Hashtable>(new IntPtr(p + 0x018), ReversePrism.DataModels.Hashtable.FromPointer); // 0x18 Namespaces                  ( ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Autogenerated                             = GetObject<Hashtable>(new IntPtr(p + 0x020), ReversePrism.DataModels.Hashtable.FromPointer); // 0x20 Autogenerated               ( ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Prefixes                                  = GetObject<Hashtable>(new IntPtr(p + 0x028), ReversePrism.DataModels.Hashtable.FromPointer); // 0x28 Prefixes                    ( ModelClassType Hashtable Hashtable Hashtable Pointer )
            value.Ds                                        = GetObject<DataSet>(new IntPtr(p + 0x030), ReversePrism.DataModels.DataSet.FromPointer); // 0x30 Ds                          ( ModelClassType DataSet DataSet DataSet Pointer )
            value.Tables                                    = GetObject<ArrayList>(new IntPtr(p + 0x038), ReversePrism.DataModels.ArrayList.FromPointer); // 0x38 Tables                      ( ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Relations                                 = GetObject<ArrayList>(new IntPtr(p + 0x040), ReversePrism.DataModels.ArrayList.FromPointer); // 0x40 Relations                   ( ModelClassType ArrayList ArrayList ArrayList Pointer )
            value.Dc                                        = GetObject<XmlDocument>(new IntPtr(p + 0x048), ReversePrism.DataModels.XmlDocument.FromPointer); // 0x48 Dc                          ( ModelClassType XmlDocument XmlDocument XmlDocument Pointer )
            value.SRoot                                     = GetObject<XmlElement>(new IntPtr(p + 0x050), ReversePrism.DataModels.XmlElement.FromPointer); // 0x50 SRoot                       ( ModelClassType XmlElement XmlElement XmlElement Pointer )
            value.PrefixCount                               = GetInt32(new IntPtr(p + 0x058)); // 0x58 PrefixCount                 ( ModelPrimitiveType int int int Int32 )
            value.SchFormat                                 = (SchemaFormat)GetInt32(new IntPtr(p + 0x05C)); // 0x5C SchFormat                   ( ModelEnumType SchemaFormat SchemaFormat SchemaFormat Int32 )
            value.FilePath                                  = GetString(new IntPtr(p + 0x060)); // 0x60 FilePath                    ( ModelPrimitiveType string string string String )
            value.FileName                                  = GetString(new IntPtr(p + 0x068)); // 0x68 FileName                    ( ModelPrimitiveType string string string String )
            value.FileExt                                   = GetString(new IntPtr(p + 0x070)); // 0x70 FileExt                     ( ModelPrimitiveType string string string String )
            value.DsElement                                 = GetObject<XmlElement>(new IntPtr(p + 0x078), ReversePrism.DataModels.XmlElement.FromPointer); // 0x78 DsElement                   ( ModelClassType XmlElement XmlElement XmlElement Pointer )
            value.ConstraintSeparator                       = GetObject<XmlElement>(new IntPtr(p + 0x080), ReversePrism.DataModels.XmlElement.FromPointer); // 0x80 ConstraintSeparator         ( ModelClassType XmlElement XmlElement XmlElement Pointer )

            return value;
        }
    }
}
