using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism
{
    partial class MasterData
    {
        public SortedDictionary<int, MstAccessory>?                        Accessories;
        public SortedDictionary<int, MstAccessoryResource>?                AccessoryResources;
        public SortedDictionary<int, MstAchievement>?                      Achievements;
        public SortedDictionary<string, MstAdvInfo>?                       AdvInfos;
        public List<MstAuditionSettings>?                                  AuditionSettingses;
        public SortedDictionary<int, MstBannerGenre>?                      BannerGenres;
        public List<MstBirthdayVoice>?                                     BirthdayVoices;
        public SortedDictionary<int, MstChainGroup>?                       ChainGroups;
        public SortedDictionary<int, MstChainTalk>?                        ChainTalks;
        public SortedDictionary<int, MstChainTalkText>?                    ChainTalkTexts;
        public SortedDictionary<int, MstChainUser>?                        ChainUsers;
        public SortedDictionary<int, MstChallengeTour>?                    ChallengeTours;
        public SortedDictionary<int, MstChallengeTourMission>?             ChallengeTourMissions;
        public SortedDictionary<int, MstChallengeTourStage>?               ChallengeTourStages;
        public List<MstCharacterBirthdayAdv>?                              CharacterBirthdayAdvs;
        public SortedDictionary<int, MstCharacterInfo>?                    CharacterInfos;
        public SortedDictionary<int, MstCostume>?                          Costumes;
        public SortedDictionary<int, MstCostumeResource>?                  CostumeResources;
        public SortedDictionary<int, MstCostumeSet>?                       CostumeSets;
        public List<MstCostumeShopItemGroup>?                              CostumeShopItemGroups;
        public SortedDictionary<int, MstDressOrderRecipe>?                 DressOrderRecipes;
        public SortedDictionary<int, MstDressUpRoomVoice>?                 DressUpRoomVoices;
        public SortedDictionary<int, MstEpisode>?                          Episodes;
        public SortedDictionary<int, MstEpisodeEventMissionBanner>?        EpisodeEventMissionBanners;
        public SortedDictionary<int, MstEvent>?                            Events;
        public SortedDictionary<int, MstEventAlbum>?                       EventAlbums;
        public SortedDictionary<int, MstEventIcon>?                        EventIcons;
        public SortedDictionary<int, MstEventItem>?                        EventItems;
        public SortedDictionary<int, MstEventRanking>?                     EventRankings;
        public SortedDictionary<int, MstEventStory>?                       EventStories;
        public List<MstExchangeProduct>?                                   ExchangeProducts;
        public List<MstExchangeProductFilter>?                             ExchangeProductFilters;
        public SortedDictionary<int, MstExtraStory>?                       ExtraStories;
        public SortedDictionary<int, MstExtraStoryCategory>?               ExtraStoryCategories;
        public SortedDictionary<int, MstExtraStorySubCategory>?            ExtraStorySubCategories;
        public List<MstFavoriteMark>?                                      FavoriteMarks;
        public SortedDictionary<int, MstFavoriteSchedule>?                 FavoriteSchedules;
        public SortedDictionary<int, MstFirstProduceIdol>?                 FirstProduceIdols;
        public SortedDictionary<int, MstGalleryEtcCategory>?               GalleryEtcCategories;
        public SortedDictionary<string, MstGashaResource>?                 GashaResources;
        public SortedDictionary<int, MstGashaTicket>?                      GashaTickets;
        public List<MstGiftEventReward>?                                   GiftEventRewards;
        public SortedDictionary<int, MstGiftEventTokenRelation>?           GiftEventTokenRelations;
        public SortedDictionary<int, MstHairstyle>?                        Hairstyles;
        public SortedDictionary<(int, int), MstHairstyleResource>?         HairstyleResources;
        public List<MstHelp>?                                              Helps;
        public List<MstHelpGroup>?                                         HelpGroups;
        public SortedDictionary<int, MstIdol>?                             Idols;
        public SortedDictionary<int, MstIdolSkill>?                        IdolSkills;
        public List<MstIdolSkillEffect>?                                   IdolSkillEffects;
        public SortedDictionary<int, MstIdolSkillLevelUpRecipe>?           IdolSkillLevelUpRecipes;
        public SortedDictionary<int, MstIdolStandingPosition>?             IdolStandingPositions;
        public SortedDictionary<int, MstIdolStory>?                        IdolStories;
        public SortedDictionary<int, MstItemPack>?                         ItemPacks;
        public List<MstItemProvider>?                                      ItemProviders;
        public SortedDictionary<int, MstLetter>?                           Letters;
        public SortedDictionary<int, MstLetterGroup>?                      LetterGroups;
        public SortedDictionary<int, MstLiveCenterEffect>?                 LiveCenterEffects;
        public SortedDictionary<int, MstLiveCenterEffectDetail>?           LiveCenterEffectDetails;
        public SortedDictionary<(int, int), MstLiveComboRankReward>?       LiveComboRankRewards;
        public SortedDictionary<(int, int), MstLiveComboRankTarget>?       LiveComboRankTargets;
        public List<MstLiveCutScene>?                                      LiveCutScenes;
        public List<MstLiveCutSceneCostume>?                               LiveCutSceneCostumes;
        public SortedDictionary<int, MstLiveEventBonus>?                   LiveEventBonuses;
        public SortedDictionary<(int, int), MstLiveScoreRankReward>?       LiveScoreRankRewards;
        public SortedDictionary<int, MstLiveSkillDetail>?                  LiveSkillDetails;
        public SortedDictionary<int, MstLiveSkillEffectType>?              LiveSkillEffectTypes;
        public SortedDictionary<(int, int), MstLiveSkillLevel>?            LiveSkillLevels;
        public SortedDictionary<int, MstLiveSupportEffect>?                LiveSupportEffects;
        public SortedDictionary<int, MstLiveSupportEffectDetail>?          LiveSupportEffectDetails;
        public SortedDictionary<int, MstLiveSupportEffectType>?            LiveSupportEffectTypes;
        public List<MstLiveTotalHighScoreRateReward>?                      LiveTotalHighScoreRateRewards;
        public SortedDictionary<int, MstLiveTotalTechnicalRateReward>?     LiveTotalTechnicalRateRewards;
        public List<MstLiveUnitRankingCategory>?                           LiveUnitRankingCategories;
        public SortedDictionary<int, MstLoginBonus>?                       LoginBonuses;
        public List<MstLoginBonusCostumeSet>?                              LoginBonusCostumeSets;
        public SortedDictionary<int, MstLoginBonusPass>?                   LoginBonusPasses;
        public SortedDictionary<int, MstMainStory>?                        MainStories;
        public SortedDictionary<int, MstMainStoryChapter>?                 MainStoryChapters;
        public SortedDictionary<string, MstMcsIdolOrder>?                  McsIdolOrders;
        public SortedDictionary<int, MstMissionGroup>?                     MissionGroups;
        public SortedDictionary<string, MstNcsIdolOrder>?                  NcsIdolOrders;
        public SortedDictionary<int, MstNotebook>?                         Notebooks;
        public SortedDictionary<int, MstOutgameVoiceMotion>?               OutgameVoiceMotions;
        public SortedDictionary<string, MstPcsIdolOrder>?                  PcsIdolOrders;
        public SortedDictionary<int, MstPhoneCall>?                        PhoneCalls;
        public SortedDictionary<int, MstPhoneCallText>?                    PhoneCallTexts;
        public SortedDictionary<int, MstPhoneGroup>?                       PhoneGroups;
        public SortedDictionary<int, MstPhoneUser>?                        PhoneUsers;
        public SortedDictionary<int, MstPotentialSupportSkill>?            PotentialSupportSkills;
        public SortedDictionary<int, MstProduceActionEffect>?              ProduceActionEffects;
        public SortedDictionary<int, MstProduceCardContentGroup>?          ProduceCardContentGroups;
        public SortedDictionary<int, MstProduceIdol>?                      ProduceIdols;
        public SortedDictionary<int, MstProduceIdolEvent>?                 ProduceIdolEvents;
        public SortedDictionary<int, MstProduceIdolEvolutionLevel>?        ProduceIdolEvolutionLevels;
        public SortedDictionary<int, MstProduceIdolEvolutionRecipe>?       ProduceIdolEvolutionRecipes;
        public SortedDictionary<int, MstProduceIdolLevelExp>?              ProduceIdolLevelExps;
        public SortedDictionary<int, MstProduceIdolLevelReward>?           ProduceIdolLevelRewards;
        public SortedDictionary<int, MstProduceIdolLimitBreakRecipe>?      ProduceIdolLimitBreakRecipes;
        public SortedDictionary<(int, int), MstProduceIdolPersonalLimitBreakReward>? ProduceIdolPersonalLimitBreakRewards;
        public List<MstProduceIdolReleaseCostumeSet>?                      ProduceIdolReleaseCostumeSets;
        public SortedDictionary<int, MstProduceMainIdolScenario>?          ProduceMainIdolScenarios;
        public SortedDictionary<int, MstProduceMainScenario>?              ProduceMainScenarios;
        public SortedDictionary<int, MstProducePassiveEffect>?             ProducePassiveEffects;
        public List<MstProducePromotionBanner>?                            ProducePromotionBanners;
        public List<MstProduceUniqueCutScene>?                             ProduceUniqueCutScenes;
        public SortedDictionary<int, MstProductType>?                      ProductTypes;
        public SortedDictionary<int, MstRecoveryDrink>?                    RecoveryDrinks;
        public List<MstScheduleType>?                                      ScheduleTypes;
        public SortedDictionary<int, MstSeasonMission>?                    SeasonMissions;
        public SortedDictionary<int, MstShinyCompetition>?                 ShinyCompetitions;
        public List<MstShinyCompetitionIdol>?                              ShinyCompetitionIdols;
        public SortedDictionary<int, MstShinyCompetitionProduceBonus>?     ShinyCompetitionProduceBonuses;
        public SortedDictionary<int, MstShinyCompetitionProduceBonusCondition>? ShinyCompetitionProduceBonusConditions;
        public SortedDictionary<int, MstShinyCompetitionRanking>?          ShinyCompetitionRankings;
        public SortedDictionary<int, MstSkillBufferDisplay>?               SkillBufferDisplays;
        public SortedDictionary<int, MstSong>?                             Songs;
        public SortedDictionary<(int, int), MstSongDifficultyLevel>?       SongDifficultyLevels;
        public SortedDictionary<int, MstSongOverrideOnStageIdolCount>?     SongOverrideOnStageIdolCounts;
        public SortedDictionary<int, MstSongPartsCharacter>?               SongPartsCharacters;
        public SortedDictionary<int, MstSongPositionExample>?              SongPositionExamples;
        public SortedDictionary<int, MstSongType>?                         SongTypes;
        public SortedDictionary<int, MstSpecialMission>?                   SpecialMissions;
        public SortedDictionary<int, MstStarGrowth>?                       StarGrowths;
        public SortedDictionary<int, MstStreamProgram>?                    StreamPrograms;
        public List<MstSubSeasonOpeningAdvOption>?                         SubSeasonOpeningAdvOptions;
        public SortedDictionary<int, MstSupportCharacter>?                 SupportCharacters;
        public SortedDictionary<int, MstSupportCharacterEvent>?            SupportCharacterEvents;
        public List<MstSupportCharacterLevelExp>?                          SupportCharacterLevelExps;
        public SortedDictionary<int, MstSupportCharacterLevelReward>?      SupportCharacterLevelRewards;
        public List<MstSupportCharacterLimitBreakBonus>?                   SupportCharacterLimitBreakBonuses;
        public SortedDictionary<int, MstSupportCharacterLimitBreakRecipe>? SupportCharacterLimitBreakRecipes;
        public SortedDictionary<int, MstSupportEffect>?                    SupportEffects;
        public List<MstTips>?                                              Tipses;
        public SortedDictionary<int, MstTipsCategory>?                     TipsCategories;
        public SortedDictionary<int, MstTrainingTicket>?                   TrainingTickets;
        public List<MstTutorial>?                                          Tutorials;
        public SortedDictionary<int, MstTwestaArticle>?                    TwestaArticles;
        public SortedDictionary<int, MstTwestaComment>?                    TwestaComments;
        public SortedDictionary<int, MstTwestaUser>?                       TwestaUsers;
        public SortedDictionary<int, MstUnit>?                             Units;
        public SortedDictionary<int, MstVoiceResource>?                    VoiceResources;

        private void Load(BinaryReader r)
        {
            EntryCount  = r.ReadByte();

            Load(r, nameof(Accessories),                        out Accessories);
            Load(r, nameof(AccessoryResources),                 out AccessoryResources);
            Load(r, nameof(Achievements),                       out Achievements);
            Load(r, nameof(AdvInfos),                           out AdvInfos);
            Load(r, nameof(AuditionSettingses),                 out AuditionSettingses);
            Load(r, nameof(BannerGenres),                       out BannerGenres);
            Load(r, nameof(BirthdayVoices),                     out BirthdayVoices);
            Load(r, nameof(ChainGroups),                        out ChainGroups);
            Load(r, nameof(ChainTalks),                         out ChainTalks);
            Load(r, nameof(ChainTalkTexts),                     out ChainTalkTexts);
            Load(r, nameof(ChainUsers),                         out ChainUsers);
            Load(r, nameof(ChallengeTours),                     out ChallengeTours);
            Load(r, nameof(ChallengeTourMissions),              out ChallengeTourMissions);
            Load(r, nameof(ChallengeTourStages),                out ChallengeTourStages);
            Load(r, nameof(CharacterBirthdayAdvs),              out CharacterBirthdayAdvs);
            Load(r, nameof(CharacterInfos),                     out CharacterInfos);
            Load(r, nameof(Costumes),                           out Costumes);
            Load(r, nameof(CostumeResources),                   out CostumeResources);
            Load(r, nameof(CostumeSets),                        out CostumeSets);
            Load(r, nameof(CostumeShopItemGroups),              out CostumeShopItemGroups);
            Load(r, nameof(DressOrderRecipes),                  out DressOrderRecipes);
            Load(r, nameof(DressUpRoomVoices),                  out DressUpRoomVoices);
            Load(r, nameof(Episodes),                           out Episodes);
            Load(r, nameof(EpisodeEventMissionBanners),         out EpisodeEventMissionBanners);
            Load(r, nameof(Events),                             out Events);
            Load(r, nameof(EventAlbums),                        out EventAlbums);
            Load(r, nameof(EventIcons),                         out EventIcons);
            Load(r, nameof(EventItems),                         out EventItems);
            Load(r, nameof(EventRankings),                      out EventRankings);
            Load(r, nameof(EventStories),                       out EventStories);
            Load(r, nameof(ExchangeProducts),                   out ExchangeProducts);
            Load(r, nameof(ExchangeProductFilters),             out ExchangeProductFilters);
            Load(r, nameof(ExtraStories),                       out ExtraStories);
            Load(r, nameof(ExtraStoryCategories),               out ExtraStoryCategories);
            Load(r, nameof(ExtraStorySubCategories),            out ExtraStorySubCategories);
            Load(r, nameof(FavoriteMarks),                      out FavoriteMarks);
            Load(r, nameof(FavoriteSchedules),                  out FavoriteSchedules);
            Load(r, nameof(FirstProduceIdols),                  out FirstProduceIdols);
            Load(r, nameof(GalleryEtcCategories),               out GalleryEtcCategories);
            Load(r, nameof(GashaResources),                     out GashaResources);
            Load(r, nameof(GashaTickets),                       out GashaTickets);
            Load(r, nameof(GiftEventRewards),                   out GiftEventRewards);
            Load(r, nameof(GiftEventTokenRelations),            out GiftEventTokenRelations);
            Load(r, nameof(Hairstyles),                         out Hairstyles);
            Load(r, nameof(HairstyleResources),                 out HairstyleResources);
            Load(r, nameof(Helps),                              out Helps);
            Load(r, nameof(HelpGroups),                         out HelpGroups);
            Load(r, nameof(Idols),                              out Idols);
            Load(r, nameof(IdolSkills),                         out IdolSkills);
            Load(r, nameof(IdolSkillEffects),                   out IdolSkillEffects);
            Load(r, nameof(IdolSkillLevelUpRecipes),            out IdolSkillLevelUpRecipes);
            Load(r, nameof(IdolStandingPositions),              out IdolStandingPositions);
            Load(r, nameof(IdolStories),                        out IdolStories);
            Load(r, nameof(ItemPacks),                          out ItemPacks);
            Load(r, nameof(ItemProviders),                      out ItemProviders);
            Load(r, nameof(Letters),                            out Letters);
            Load(r, nameof(LetterGroups),                       out LetterGroups);
            Load(r, nameof(LiveCenterEffects),                  out LiveCenterEffects);
            Load(r, nameof(LiveCenterEffectDetails),            out LiveCenterEffectDetails);
            Load(r, nameof(LiveComboRankRewards),               out LiveComboRankRewards);
            Load(r, nameof(LiveComboRankTargets),               out LiveComboRankTargets);
            Load(r, nameof(LiveCutScenes),                      out LiveCutScenes);
            Load(r, nameof(LiveCutSceneCostumes),               out LiveCutSceneCostumes);
            Load(r, nameof(LiveEventBonuses),                   out LiveEventBonuses);
            Load(r, nameof(LiveScoreRankRewards),               out LiveScoreRankRewards);
            Load(r, nameof(LiveSkillDetails),                   out LiveSkillDetails);
            Load(r, nameof(LiveSkillEffectTypes),               out LiveSkillEffectTypes);
            Load(r, nameof(LiveSkillLevels),                    out LiveSkillLevels);
            Load(r, nameof(LiveSupportEffects),                 out LiveSupportEffects);
            Load(r, nameof(LiveSupportEffectDetails),           out LiveSupportEffectDetails);
            Load(r, nameof(LiveSupportEffectTypes),             out LiveSupportEffectTypes);
            Load(r, nameof(LiveTotalHighScoreRateRewards),      out LiveTotalHighScoreRateRewards);
            Load(r, nameof(LiveTotalTechnicalRateRewards),      out LiveTotalTechnicalRateRewards);
            Load(r, nameof(LiveUnitRankingCategories),          out LiveUnitRankingCategories);
            Load(r, nameof(LoginBonuses),                       out LoginBonuses);
            Load(r, nameof(LoginBonusCostumeSets),              out LoginBonusCostumeSets);
            Load(r, nameof(LoginBonusPasses),                   out LoginBonusPasses);
            Load(r, nameof(MainStories),                        out MainStories);
            Load(r, nameof(MainStoryChapters),                  out MainStoryChapters);
            Load(r, nameof(McsIdolOrders),                      out McsIdolOrders);
            Load(r, nameof(MissionGroups),                      out MissionGroups);
            Load(r, nameof(NcsIdolOrders),                      out NcsIdolOrders);
            Load(r, nameof(Notebooks),                          out Notebooks);
            Load(r, nameof(OutgameVoiceMotions),                out OutgameVoiceMotions);
            Load(r, nameof(PcsIdolOrders),                      out PcsIdolOrders);
            Load(r, nameof(PhoneCalls),                         out PhoneCalls);
            Load(r, nameof(PhoneCallTexts),                     out PhoneCallTexts);
            Load(r, nameof(PhoneGroups),                        out PhoneGroups);
            Load(r, nameof(PhoneUsers),                         out PhoneUsers);
            Load(r, nameof(PotentialSupportSkills),             out PotentialSupportSkills);
            Load(r, nameof(ProduceActionEffects),               out ProduceActionEffects);
            Load(r, nameof(ProduceCardContentGroups),           out ProduceCardContentGroups);
            Load(r, nameof(ProduceIdols),                       out ProduceIdols);
            Load(r, nameof(ProduceIdolEvents),                  out ProduceIdolEvents);
            Load(r, nameof(ProduceIdolEvolutionLevels),         out ProduceIdolEvolutionLevels);
            Load(r, nameof(ProduceIdolEvolutionRecipes),        out ProduceIdolEvolutionRecipes);
            Load(r, nameof(ProduceIdolLevelExps),               out ProduceIdolLevelExps);
            Load(r, nameof(ProduceIdolLevelRewards),            out ProduceIdolLevelRewards);
            Load(r, nameof(ProduceIdolLimitBreakRecipes),       out ProduceIdolLimitBreakRecipes);
            Load(r, nameof(ProduceIdolPersonalLimitBreakRewards),out ProduceIdolPersonalLimitBreakRewards);
            Load(r, nameof(ProduceIdolReleaseCostumeSets),      out ProduceIdolReleaseCostumeSets);
            Load(r, nameof(ProduceMainIdolScenarios),           out ProduceMainIdolScenarios);
            Load(r, nameof(ProduceMainScenarios),               out ProduceMainScenarios);
            Load(r, nameof(ProducePassiveEffects),              out ProducePassiveEffects);
            Load(r, nameof(ProducePromotionBanners),            out ProducePromotionBanners);
            Load(r, nameof(ProduceUniqueCutScenes),             out ProduceUniqueCutScenes);
            Load(r, nameof(ProductTypes),                       out ProductTypes);
            Load(r, nameof(RecoveryDrinks),                     out RecoveryDrinks);
            Load(r, nameof(ScheduleTypes),                      out ScheduleTypes);
            Load(r, nameof(SeasonMissions),                     out SeasonMissions);
            Load(r, nameof(ShinyCompetitions),                  out ShinyCompetitions);
            Load(r, nameof(ShinyCompetitionIdols),              out ShinyCompetitionIdols);
            Load(r, nameof(ShinyCompetitionProduceBonuses),     out ShinyCompetitionProduceBonuses);
            Load(r, nameof(ShinyCompetitionProduceBonusConditions),out ShinyCompetitionProduceBonusConditions);
            Load(r, nameof(ShinyCompetitionRankings),           out ShinyCompetitionRankings);
            Load(r, nameof(SkillBufferDisplays),                out SkillBufferDisplays);
            Load(r, nameof(Songs),                              out Songs);
            Load(r, nameof(SongDifficultyLevels),               out SongDifficultyLevels);
            Load(r, nameof(SongOverrideOnStageIdolCounts),      out SongOverrideOnStageIdolCounts);
            Load(r, nameof(SongPartsCharacters),                out SongPartsCharacters);
            Load(r, nameof(SongPositionExamples),               out SongPositionExamples);
            Load(r, nameof(SongTypes),                          out SongTypes);
            Load(r, nameof(SpecialMissions),                    out SpecialMissions);
            Load(r, nameof(StarGrowths),                        out StarGrowths);
            Load(r, nameof(StreamPrograms),                     out StreamPrograms);
            Load(r, nameof(SubSeasonOpeningAdvOptions),         out SubSeasonOpeningAdvOptions);
            Load(r, nameof(SupportCharacters),                  out SupportCharacters);
            Load(r, nameof(SupportCharacterEvents),             out SupportCharacterEvents);
            Load(r, nameof(SupportCharacterLevelExps),          out SupportCharacterLevelExps);
            Load(r, nameof(SupportCharacterLevelRewards),       out SupportCharacterLevelRewards);
            Load(r, nameof(SupportCharacterLimitBreakBonuses),  out SupportCharacterLimitBreakBonuses);
            Load(r, nameof(SupportCharacterLimitBreakRecipes),  out SupportCharacterLimitBreakRecipes);
            Load(r, nameof(SupportEffects),                     out SupportEffects);    // 1E94CE 4388 MstSupportEffect
            Load(r, nameof(Tipses),                             out Tipses);            // 210F06 23 MstTips
            Load(r, nameof(TipsCategories),                     out TipsCategories);    // 211035 4 MstTipsCategory
            r.ReadInt32();  // Ç»Ç∫ïKóvÇ»ÇÃÇ©ÅH
            Load(r, nameof(TrainingTickets),                    out TrainingTickets);   // 21108D 3 MstTrainingTicket
            Load(r, nameof(Tutorials),                          out Tutorials);         // 2110B8 11 MstTutorial
            Load(r, nameof(TwestaArticles),                     out TwestaArticles);    // 21111F 277 MstTwestaArticle
            Load(r, nameof(TwestaComments),                     out TwestaComments);    // 211F34 416 MstTwestaComment
            Load(r, nameof(TwestaUsers),                        out TwestaUsers);       // 212758 29 MstTwestaUser
            Load(r, nameof(Units),                              out Units);             // 2127ED 10 MstUnit
            Load(r, nameof(VoiceResources),                     out VoiceResources);    // 2128E1 7987 MstVoiceResource

        }
    }
}
