using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism
{
    partial  class MasterData
    {
        public _00_MstCharacterInfo[]?                      CharacterInfos;
        public _01_MstIdol[]?                               Idols;
        public _02_MstIdolStandingPosition[]?               IdolStandingPositions;
        public _03_MstCostumeSet[]?                         CostumeSets;
        public _04_MstCostume[]?                            Costumes;
        public _05_MstCostumeResource[]?                    CostumeResources;
        public _06_MstHairstyle[]?                          Hairstyles;
        public _07_MstHairstyleResource[]?                  HairstyleResources;
        public _08_MstAccessorie[]?                         Accessories;
        public _09_MstAccessoryResource[]?                  AccessoryResources;
        public _10_MstFavoriteMark[]?                       FavoriteMarks;
        public _11_MstProductType[]?                        ProductTypes;
        public _12_MstProduceIdolLimitBreakRecipe[]?        ProduceIdolLimitBreakRecipes;
        public _13_MstProduceIdolEvolutionRecipe[]?         ProduceIdolEvolutionRecipes;
        public _14_MstSupportCharacterLevelExp[]?           SupportCharacterLevelExps;
        public _15_MstSupportCharacterLimitBreakRecipe[]?   SupportCharacterLimitBreakRecipes;
        public _16_MstOutgameVoiceMotion[]?                 OutgameVoiceMotions;
        public _17_MstUnit[]?                               Units;
        public _18_MstItemProvider[]?                       ItemProviders;
        public _19_MstTrainingTicket[]?                     TrainingTickets;
        public _20_MstProduceActionEffectDisplay[]?         ProduceActionEffectDisplays;
        public _21_MstVoiceResource[]?                      VoiceResources;
        public _22_MstSupportEffect[]?                      SupportEffects;
        public _23_MstProducePassiveEffect[]?               ProducePassiveEffects;
        public _24_MstSupportCharacterLimitBreakBonuse[]?   SupportCharacterLimitBreakBonuses;
        public _25_MstTip[]?                                Tips;
        public _26_MstTipsCategor[]?                        TipsCategory;
        public _27_MstExchangeProductFilter[]?              ExchangeProductFilters;
        public _28_MstPotentialLiveSkill[]?                 PotentialLiveSkills;
        public _29_MstPotentialLiveSkillLevel[]?            PotentialLiveSkillLevels;
        public _30_MstLiveSkillEffect[]?                    LiveSkillEffects;
        public _31_MstChainGroup[]?                         ChainGroups;
        public _32_MstPhoneUser[]?                          PhoneUsers;
        public _33_MstPotentialSupportSkill[]?              PotentialSupportSkills;
        public _34_MstHelp[]?                               Helps;
        public _35_MstBirthdayVoic[]?                       BirthdayVoice;
        public _36_MstHelpGroup[]?                          HelpGroups;
        public _37_MstIdolStorie[]?                         IdolStories;
        public _38_MstTitleImage[]?                         TitleImages;
        public _39_MstSong[]?                               Songs;
        public _40_MstAdvInfo[]?                            AdvInfos;
        public _41_MstTwestaUser[]?                         TwestaUsers;
        public _42_MstChainUser[]?                          ChainUsers;
        public _43_MstBannerGenr[]?                         BannerGenre;
        public _44_MstAchievemen[]?                         Achievement;
        public _45_MstEventIco[]?                           EventIcon;
        public _46_MstLoginBonu[]?                          LoginBonus;
        public _47_MstLoginBonusGraffit[]?                  LoginBonusGraffiti;
        public _48_MstEpisode[]?                            Episodes;
        public _49_MstProduceCardContentGroup[]?            ProduceCardContentGroups;
        public _50_MstProduceActionEffect[]?                ProduceActionEffects;
        public _51_MstEvent[]?                              Events;
        public _52_MstProduceIdol[]?                        ProduceIdols;
        public _53_MstTwestaArticle[]?                      TwestaArticles;
        public _54_MstSupportCharacter[]?                   SupportCharacters;
        public _55_MstGeneralItem[]?                        GeneralItems;
        public _56_MstRecoveryDrink[]?                      RecoveryDrinks;
        public _57_MstEpisodeEventMissionBanner[]?          EpisodeEventMissionBanners;
        public _58_MstMainStoryChapter[]?                   MainStoryChapters;
        public _59_MstMainStorie[]?                         MainStories;
        public _60_MstExtraStoryCategorie[]?                ExtraStoryCategories;
        public _61_MstExtraStorySubCategorie[]?             ExtraStorySubCategories;
        public _62_MstExtraStorie[]?                        ExtraStories;
        public _63_MstEventStorie[]?                        EventStories;
        public _64_MstChallengeTourStage[]?                 ChallengeTourStages;
        public _65_MstChallengeTourMission[]?               ChallengeTourMissions;
        public _66_MstChallengeTour[]?                      ChallengeTours;
        public _67_MstChallengeTourRival[]?                 ChallengeTourRivals;
        public _68_MstSeasonMission[]?                      SeasonMissions;
        public _69_MstGashaResource[]?                      GashaResources;
        public _70_MstPhoneCall[]?                          PhoneCalls;
        public _71_MstGashaTicket[]?                        GashaTickets;
        public _72_MstGashaCompensationTicket[]?            GashaCompensationTickets;
        public _73_MstGashaToken[]?                         GashaTokens;
        public _74_MstSelectionTicket[]?                    SelectionTickets;
        public _75_MstCostumeTicket[]?                      CostumeTickets;
        public _76_MstProduceStrategyType[]?                ProduceStrategyTypes;
        public _77_MstChainTalkText[]?                      ChainTalkTexts;
        public _78_MstProduceAuditionSetting[]?             ProduceAuditionSettings;
      //public _79_MstFavoriteMarkId[]?                     FavoriteMarkIds;
    }
}
