using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReversePrism
{
    partial class MasterData
    {
        public Dictionary<int, MstCharacterInfo>?                          CharacterInfos;
        public Dictionary<int, MstIdol>?                                   Idols;
        public Dictionary<int, MstIdolStandingPosition>?                   IdolStandingPositions;
        public Dictionary<int, MstCostumeSet>?                             CostumeSets;
        public Dictionary<int, MstCostume>?                                Costumes;
        public Dictionary<int, MstCostumeResource>?                        CostumeResources;
        public Dictionary<int, MstHairstyle>?                              Hairstyles;
        public Dictionary<(int, int), MstHairstyleResource>?               HairstyleResources;
        public Dictionary<int, MstAccessory>?                              Accessories;
        public Dictionary<int, MstAccessoryResource>?                      AccessoryResources;
        public MstFavoriteMark[]?                                          FavoriteMarks;
        public Dictionary<int, MstProductType>?                            ProductTypes;
        public Dictionary<int, MstProduceIdolLimitBreakRecipe>?            ProduceIdolLimitBreakRecipes;
        public Dictionary<int, MstProduceIdolEvolutionRecipe>?             ProduceIdolEvolutionRecipes;
        public Dictionary<int, MstSupportCharacterLevelExp>?               SupportCharacterLevelExps;
        public Dictionary<int, MstSupportCharacterLimitBreakRecipe>?       SupportCharacterLimitBreakRecipes;
        public Dictionary<int, MstOutgameVoiceMotion>?                     OutgameVoiceMotions;
        public Dictionary<int, MstUnit>?                                   Units;
        public MstItemProvider[]?                                          ItemProviders;
        public Dictionary<int, MstTrainingTicket>?                         TrainingTickets;
        public MstProduceActionEffectDisplay[]?                            ProduceActionEffectDisplays;
        public Dictionary<int, MstVoiceResource>?                          VoiceResources;
        public Dictionary<int, MstSupportEffect>?                          SupportEffects;
        public Dictionary<int, MstProducePassiveEffect>?                   ProducePassiveEffects;
        public MstSupportCharacterLimitBreakBonus[]?                       SupportCharacterLimitBreakBonuses;
        public MstTips[]?                                                  Tips;
        public Dictionary<int, MstTipsCategory>?                           TipsCategory;
        public MstExchangeProductFilter[]?                                 ExchangeProductFilters;
        public MstPotentialLiveSkill[]?                                    PotentialLiveSkills;
        public Dictionary<int, MstPotentialLiveSkillLevel>?                PotentialLiveSkillLevels;
        public Dictionary<int, MstLiveSkillEffect>?                        LiveSkillEffects;
        public Dictionary<int, MstChainGroup>?                             ChainGroups;
        public Dictionary<int, MstPhoneUser>?                              PhoneUsers;
        public Dictionary<int, MstPotentialSupportSkill>?                  PotentialSupportSkills;
        public MstHelp[]?                                                  Helps;
        public MstBirthdayVoice[]?                                         BirthdayVoice;
        public MstHelpGroup[]?                                             HelpGroups;
        public Dictionary<int, MstIdolStory>?                              IdolStories;
        public Dictionary<int, MstSong>?                                   Songs;
        public MstAdvInfo[]?                                               AdvInfos;
        public Dictionary<int, MstTwestaUser>?                             TwestaUsers;
        public Dictionary<int, MstChainUser>?                              ChainUsers;
        public Dictionary<int, MstBannerGenre>?                            BannerGenre;
        public Dictionary<int, MstAchievement>?                            Achievement;
        public Dictionary<int, MstEventIcon>?                              EventIcon;
        public Dictionary<int, MstLoginBonus>?                             LoginBonus;
        public Dictionary<int, MstLoginBonusGraffiti>?                     LoginBonusGraffiti;
        public MstEpisode[]?                                               Episodes;
        public MstProduceCardContentGroup[]?                               ProduceCardContentGroups;
        public Dictionary<int, MstProduceActionEffect>?                    ProduceActionEffects;
        public Dictionary<int, MstEvent>?                                  Events;
        public Dictionary<int, MstProduceIdol>?                            ProduceIdols;
        public Dictionary<int, MstTwestaArticle>?                          TwestaArticles;
        public Dictionary<int, MstSupportCharacter>?                       SupportCharacters;
        public MstGeneralItem[]?                                           GeneralItems;
        public Dictionary<int, MstRecoveryDrink>?                          RecoveryDrinks;
        public Dictionary<int, MstEpisodeEventMissionBanner>?              EpisodeEventMissionBanners;
        public Dictionary<int, MstMainStoryChapter>?                       MainStoryChapters;
        public Dictionary<int, MstMainStory>?                              MainStories;
        public Dictionary<int, MstExtraStoryCategory>?                     ExtraStoryCategories;
        public Dictionary<int, MstExtraStorySubCategory>?                  ExtraStorySubCategories;
        public Dictionary<int, MstExtraStory>?                             ExtraStories;
        public Dictionary<int, MstEventStory>?                             EventStories;
        public Dictionary<int, MstChallengeTourStage>?                     ChallengeTourStages;
        public Dictionary<int, MstChallengeTourMission>?                   ChallengeTourMissions;
        public Dictionary<int, MstChallengeTour>?                          ChallengeTours;
        public MstChallengeTourRival[]?                                    ChallengeTourRivals;
        public Dictionary<int, MstSeasonMission>?                          SeasonMissions;
        public Dictionary<string, MstGashaResource>?                       GashaResources;
        public Dictionary<int, MstPhoneCall>?                              PhoneCalls;
        public Dictionary<int, MstGashaTicket>?                            GashaTickets;
        public Dictionary<int, MstGashaCompensationTicket>?                GashaCompensationTickets;
        public Dictionary<int, MstGashaToken>?                             GashaTokens;
        public Dictionary<int, MstSelectionTicket>?                        SelectionTickets;
        public Dictionary<int, MstCostumeTicket>?                          CostumeTickets;
        public MstProduceStrategyType[]?                                   ProduceStrategyTypes;
        public Dictionary<int, MstStreamProgram>?                          StreamPrograms;
        public Dictionary<int, MstStreamProgramCast>?                      StreamProgramCasts;
        public Dictionary<int, MstChainTalkText>?                          ChainTalkTexts;
        public MstAuditionSettings[]?                                      ProduceAuditionSettings;
        public Dictionary<int, MstSongType>?                               SongTypes;
        public Dictionary<int, MstLetterGroup>?                            LetterGroups;
        public MstLetter[]?                                                Letters;
        public MstGalleryEtcCategory[]?                                    GalleryEtcCategories;
        public Dictionary<int, MstLiveEventBonus>?                         LiveEventBonuses;
        public Dictionary<int, MstSkillBufferDisplay>?                     SkillBufferDisplays;
        public MstShinyPartyToken[]?                                       ShinyPartyTokens;
        public Dictionary<int, MstTwestaComment>?                          TwestaComments;
        public MstPvpIngameSettings[]?                                     PvpIngameSettings;
        public Dictionary<int, MstChainTalk>?                              ChainTalks;
        public MstSubSeasonOpeningAdvOption[]?                             SubSeasonOpeningAdvOption;

        private void Load(BinaryReader r)
        {
            EntryCount  = r.ReadByte();

            Load(r, nameof(CharacterInfos),                     out CharacterInfos);
            Load(r, nameof(Idols),                              out Idols);
            Load(r, nameof(IdolStandingPositions),              out IdolStandingPositions);
            Load(r, nameof(CostumeSets),                        out CostumeSets);
            Load(r, nameof(Costumes),                           out Costumes);
            Load(r, nameof(CostumeResources),                   out CostumeResources);
            Load(r, nameof(Hairstyles),                         out Hairstyles);
            Load(r, nameof(HairstyleResources),                 out HairstyleResources);
            Load(r, nameof(Accessories),                        out Accessories);
            Load(r, nameof(AccessoryResources),                 out AccessoryResources);
            Load(r, nameof(FavoriteMarks),                      out FavoriteMarks);
            Load(r, nameof(ProductTypes),                       out ProductTypes);
            Load(r, nameof(ProduceIdolLimitBreakRecipes),       out ProduceIdolLimitBreakRecipes);
            Load(r, nameof(ProduceIdolEvolutionRecipes),        out ProduceIdolEvolutionRecipes);
            Load(r, nameof(SupportCharacterLevelExps),          out SupportCharacterLevelExps);
            Load(r, nameof(SupportCharacterLimitBreakRecipes),  out SupportCharacterLimitBreakRecipes);
            Load(r, nameof(OutgameVoiceMotions),                out OutgameVoiceMotions);
            Load(r, nameof(Units),                              out Units);
            Load(r, nameof(ItemProviders),                      out ItemProviders);
            Load(r, nameof(TrainingTickets),                    out TrainingTickets);
            Load(r, nameof(ProduceActionEffectDisplays),        out ProduceActionEffectDisplays);
            Load(r, nameof(VoiceResources),                     out VoiceResources);
            Load(r, nameof(SupportEffects),                     out SupportEffects);
            Load(r, nameof(ProducePassiveEffects),              out ProducePassiveEffects);
            Load(r, nameof(SupportCharacterLimitBreakBonuses),  out SupportCharacterLimitBreakBonuses);
            Load(r, nameof(Tips),                               out Tips);
            Load(r, nameof(TipsCategory),                       out TipsCategory);
            Load(r, nameof(ExchangeProductFilters),             out ExchangeProductFilters);
            Load(r, nameof(PotentialLiveSkills),                out PotentialLiveSkills);
            Load(r, nameof(PotentialLiveSkillLevels),           out PotentialLiveSkillLevels);
            Load(r, nameof(LiveSkillEffects),                   out LiveSkillEffects);
            Load(r, nameof(ChainGroups),                        out ChainGroups);
            Load(r, nameof(PhoneUsers),                         out PhoneUsers);
            Load(r, nameof(PotentialSupportSkills),             out PotentialSupportSkills);
            Load(r, nameof(Helps),                              out Helps);
            Load(r, nameof(BirthdayVoice),                      out BirthdayVoice);
            Load(r, nameof(HelpGroups),                         out HelpGroups);
            Load(r, nameof(IdolStories),                        out IdolStories);
            Load(r, "TitleImages");
            Load(r, nameof(Songs),                              out Songs);
            Load(r, nameof(AdvInfos),                           out AdvInfos);
            Load(r, nameof(TwestaUsers),                        out TwestaUsers);
            Load(r, nameof(ChainUsers),                         out ChainUsers);
            Load(r, nameof(BannerGenre),                        out BannerGenre);
            Load(r, nameof(Achievement),                        out Achievement);
            Load(r, nameof(EventIcon),                          out EventIcon);
            Load(r, nameof(LoginBonus),                         out LoginBonus);
            Load(r, nameof(LoginBonusGraffiti),                 out LoginBonusGraffiti);
            Load(r, nameof(Episodes),                           out Episodes);
            Load(r, nameof(ProduceCardContentGroups),           out ProduceCardContentGroups);
            Load(r, nameof(ProduceActionEffects),               out ProduceActionEffects);
            Load(r, nameof(Events),                             out Events);
            Load(r, nameof(ProduceIdols),                       out ProduceIdols);
            Load(r, nameof(TwestaArticles),                     out TwestaArticles);
            Load(r, nameof(SupportCharacters),                  out SupportCharacters);
            Load(r, nameof(GeneralItems),                       out GeneralItems);
            Load(r, nameof(RecoveryDrinks),                     out RecoveryDrinks);
            Load(r, nameof(EpisodeEventMissionBanners),         out EpisodeEventMissionBanners);
            Load(r, nameof(MainStoryChapters),                  out MainStoryChapters);
            Load(r, nameof(MainStories),                        out MainStories);
            Load(r, nameof(ExtraStoryCategories),               out ExtraStoryCategories);
            Load(r, nameof(ExtraStorySubCategories),            out ExtraStorySubCategories);
            Load(r, nameof(ExtraStories),                       out ExtraStories);
            Load(r, nameof(EventStories),                       out EventStories);
            Load(r, nameof(ChallengeTourStages),                out ChallengeTourStages);
            Load(r, nameof(ChallengeTourMissions),              out ChallengeTourMissions);
            Load(r, nameof(ChallengeTours),                     out ChallengeTours);
            Load(r, nameof(ChallengeTourRivals),                out ChallengeTourRivals);
            Load(r, nameof(SeasonMissions),                     out SeasonMissions);
            Load(r, nameof(GashaResources),                     out GashaResources);
            Load(r, nameof(PhoneCalls),                         out PhoneCalls);
            Load(r, nameof(GashaTickets),                       out GashaTickets);
            Load(r, nameof(GashaCompensationTickets),           out GashaCompensationTickets);
            Load(r, nameof(GashaTokens),                        out GashaTokens);
            Load(r, nameof(SelectionTickets),                   out SelectionTickets);
            Load(r, nameof(CostumeTickets),                     out CostumeTickets);
            Load(r, nameof(ProduceStrategyTypes),               out ProduceStrategyTypes);
            Load(r, nameof(StreamPrograms),                     out StreamPrograms);
            Load(r, nameof(StreamProgramCasts),                 out StreamProgramCasts);
            Load(r, nameof(ChainTalkTexts),                     out ChainTalkTexts);
            Load(r, nameof(ProduceAuditionSettings),            out ProduceAuditionSettings);
            Load(r, nameof(SongTypes),                          out SongTypes);
            Load(r, nameof(LetterGroups),                       out LetterGroups);
            Load(r, nameof(Letters),                            out Letters);
            Load(r, nameof(GalleryEtcCategories),               out GalleryEtcCategories);
            Load(r, nameof(LiveEventBonuses),                   out LiveEventBonuses);
            Load(r, nameof(SkillBufferDisplays),                out SkillBufferDisplays);
            Load(r, nameof(ShinyPartyTokens),                   out ShinyPartyTokens);
            Load(r, nameof(TwestaComments),                     out TwestaComments);
            Load(r, nameof(PvpIngameSettings),                  out PvpIngameSettings);
            Load(r, nameof(ChainTalks),                         out ChainTalks);
            Load(r, nameof(SubSeasonOpeningAdvOption),          out SubSeasonOpeningAdvOption);
        }
    }
}
